// Code generated by go-swagger; DO NOT EDIT.

package alert_watchers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.dev.purestorage.com/FlashArray/terraform-provider-cbs/cbs/internal/array/faclient/2.4/models"
)

// GetAPI24AlertWatchersTestReader is a Reader for the GetAPI24AlertWatchersTest structure.
type GetAPI24AlertWatchersTestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPI24AlertWatchersTestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetApi24AlertWatchersTestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetApi24AlertWatchersTestBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetApi24AlertWatchersTestOK creates a GetApi24AlertWatchersTestOK with default headers values
func NewGetApi24AlertWatchersTestOK() *GetApi24AlertWatchersTestOK {
	return &GetApi24AlertWatchersTestOK{}
}

/*GetApi24AlertWatchersTestOK handles this case with default header values.

OK
*/
type GetApi24AlertWatchersTestOK struct {
	Payload *models.TestResultWithResourceGetResponse
}

func (o *GetApi24AlertWatchersTestOK) Error() string {
	return fmt.Sprintf("[GET /api/2.4/alert-watchers/test][%d] getApi24AlertWatchersTestOK  %+v", 200, o.Payload)
}

func (o *GetApi24AlertWatchersTestOK) GetPayload() *models.TestResultWithResourceGetResponse {
	return o.Payload
}

func (o *GetApi24AlertWatchersTestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TestResultWithResourceGetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApi24AlertWatchersTestBadRequest creates a GetApi24AlertWatchersTestBadRequest with default headers values
func NewGetApi24AlertWatchersTestBadRequest() *GetApi24AlertWatchersTestBadRequest {
	return &GetApi24AlertWatchersTestBadRequest{}
}

/*GetApi24AlertWatchersTestBadRequest handles this case with default header values.

BadRequest
*/
type GetApi24AlertWatchersTestBadRequest struct {
	Payload *models.Error
}

func (o *GetApi24AlertWatchersTestBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/2.4/alert-watchers/test][%d] getApi24AlertWatchersTestBadRequest  %+v", 400, o.Payload)
}

func (o *GetApi24AlertWatchersTestBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetApi24AlertWatchersTestBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
