// Code generated by go-swagger; DO NOT EDIT.

package host_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.dev.purestorage.com/FlashArray/terraform-provider-cbs/cbs/internal/array/faclient/2.4/models"
)

// GetAPI24HostGroupsPerformanceReader is a Reader for the GetAPI24HostGroupsPerformance structure.
type GetAPI24HostGroupsPerformanceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPI24HostGroupsPerformanceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetApi24HostGroupsPerformanceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetApi24HostGroupsPerformanceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetApi24HostGroupsPerformanceOK creates a GetApi24HostGroupsPerformanceOK with default headers values
func NewGetApi24HostGroupsPerformanceOK() *GetApi24HostGroupsPerformanceOK {
	return &GetApi24HostGroupsPerformanceOK{}
}

/*GetApi24HostGroupsPerformanceOK handles this case with default header values.

OK
*/
type GetApi24HostGroupsPerformanceOK struct {
	Payload *models.ResourcePerformanceNoIDGetResponse
}

func (o *GetApi24HostGroupsPerformanceOK) Error() string {
	return fmt.Sprintf("[GET /api/2.4/host-groups/performance][%d] getApi24HostGroupsPerformanceOK  %+v", 200, o.Payload)
}

func (o *GetApi24HostGroupsPerformanceOK) GetPayload() *models.ResourcePerformanceNoIDGetResponse {
	return o.Payload
}

func (o *GetApi24HostGroupsPerformanceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResourcePerformanceNoIDGetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApi24HostGroupsPerformanceBadRequest creates a GetApi24HostGroupsPerformanceBadRequest with default headers values
func NewGetApi24HostGroupsPerformanceBadRequest() *GetApi24HostGroupsPerformanceBadRequest {
	return &GetApi24HostGroupsPerformanceBadRequest{}
}

/*GetApi24HostGroupsPerformanceBadRequest handles this case with default header values.

BadRequest
*/
type GetApi24HostGroupsPerformanceBadRequest struct {
	Payload *models.Error
}

func (o *GetApi24HostGroupsPerformanceBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/2.4/host-groups/performance][%d] getApi24HostGroupsPerformanceBadRequest  %+v", 400, o.Payload)
}

func (o *GetApi24HostGroupsPerformanceBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetApi24HostGroupsPerformanceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
