// Code generated by go-swagger; DO NOT EDIT.

package administrators

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.dev.purestorage.com/FlashArray/terraform-provider-cbs/cbs/internal/array/faclient/2.4/models"
)

// DeleteAPI24AdminsReader is a Reader for the DeleteAPI24Admins structure.
type DeleteAPI24AdminsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPI24AdminsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteApi24AdminsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteApi24AdminsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteApi24AdminsOK creates a DeleteApi24AdminsOK with default headers values
func NewDeleteApi24AdminsOK() *DeleteApi24AdminsOK {
	return &DeleteApi24AdminsOK{}
}

/*DeleteApi24AdminsOK handles this case with default header values.

OK
*/
type DeleteApi24AdminsOK struct {
}

func (o *DeleteApi24AdminsOK) Error() string {
	return fmt.Sprintf("[DELETE /api/2.4/admins][%d] deleteApi24AdminsOK ", 200)
}

func (o *DeleteApi24AdminsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteApi24AdminsBadRequest creates a DeleteApi24AdminsBadRequest with default headers values
func NewDeleteApi24AdminsBadRequest() *DeleteApi24AdminsBadRequest {
	return &DeleteApi24AdminsBadRequest{}
}

/*DeleteApi24AdminsBadRequest handles this case with default header values.

BadRequest
*/
type DeleteApi24AdminsBadRequest struct {
	Payload *models.Error
}

func (o *DeleteApi24AdminsBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/2.4/admins][%d] deleteApi24AdminsBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteApi24AdminsBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteApi24AdminsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
