// Code generated by go-swagger; DO NOT EDIT.

package administrators

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPutAPI24AdminsCacheParams creates a new PutAPI24AdminsCacheParams object
// with the default values initialized.
func NewPutAPI24AdminsCacheParams() *PutAPI24AdminsCacheParams {
	var ()
	return &PutAPI24AdminsCacheParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPI24AdminsCacheParamsWithTimeout creates a new PutAPI24AdminsCacheParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutAPI24AdminsCacheParamsWithTimeout(timeout time.Duration) *PutAPI24AdminsCacheParams {
	var ()
	return &PutAPI24AdminsCacheParams{

		timeout: timeout,
	}
}

// NewPutAPI24AdminsCacheParamsWithContext creates a new PutAPI24AdminsCacheParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutAPI24AdminsCacheParamsWithContext(ctx context.Context) *PutAPI24AdminsCacheParams {
	var ()
	return &PutAPI24AdminsCacheParams{

		Context: ctx,
	}
}

// NewPutAPI24AdminsCacheParamsWithHTTPClient creates a new PutAPI24AdminsCacheParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutAPI24AdminsCacheParamsWithHTTPClient(client *http.Client) *PutAPI24AdminsCacheParams {
	var ()
	return &PutAPI24AdminsCacheParams{
		HTTPClient: client,
	}
}

/*PutAPI24AdminsCacheParams contains all the parameters to send to the API endpoint
for the put API 24 admins cache operation typically these are written to a http.Request
*/
type PutAPI24AdminsCacheParams struct {

	/*Authorization
	  Access token (in JWT format) required to use any API endpoint (except `/oauth2`, `/login`, and `/logout`)

	*/
	Authorization *string
	/*XRequestID
	  Supplied by client during request or generated by server.

	*/
	XRequestID *string
	/*Names
	  Performs the operation on the unique name specified. Enter multiple names in comma-separated format. For example, `name01,name02`.

	*/
	Names []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put API 24 admins cache params
func (o *PutAPI24AdminsCacheParams) WithTimeout(timeout time.Duration) *PutAPI24AdminsCacheParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put API 24 admins cache params
func (o *PutAPI24AdminsCacheParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put API 24 admins cache params
func (o *PutAPI24AdminsCacheParams) WithContext(ctx context.Context) *PutAPI24AdminsCacheParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put API 24 admins cache params
func (o *PutAPI24AdminsCacheParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put API 24 admins cache params
func (o *PutAPI24AdminsCacheParams) WithHTTPClient(client *http.Client) *PutAPI24AdminsCacheParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put API 24 admins cache params
func (o *PutAPI24AdminsCacheParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the put API 24 admins cache params
func (o *PutAPI24AdminsCacheParams) WithAuthorization(authorization *string) *PutAPI24AdminsCacheParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the put API 24 admins cache params
func (o *PutAPI24AdminsCacheParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithXRequestID adds the xRequestID to the put API 24 admins cache params
func (o *PutAPI24AdminsCacheParams) WithXRequestID(xRequestID *string) *PutAPI24AdminsCacheParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the put API 24 admins cache params
func (o *PutAPI24AdminsCacheParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithNames adds the names to the put API 24 admins cache params
func (o *PutAPI24AdminsCacheParams) WithNames(names []string) *PutAPI24AdminsCacheParams {
	o.SetNames(names)
	return o
}

// SetNames adds the names to the put API 24 admins cache params
func (o *PutAPI24AdminsCacheParams) SetNames(names []string) {
	o.Names = names
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPI24AdminsCacheParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}

	}

	if o.XRequestID != nil {

		// header param X-Request-ID
		if err := r.SetHeaderParam("X-Request-ID", *o.XRequestID); err != nil {
			return err
		}

	}

	valuesNames := o.Names

	joinedNames := swag.JoinByFormat(valuesNames, "csv")
	// query array param names
	if err := r.SetQueryParam("names", joinedNames...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
