// Code generated by go-swagger; DO NOT EDIT.

package volumes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAPI24VolumesReader is a Reader for the DeleteAPI24Volumes structure.
type DeleteAPI24VolumesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPI24VolumesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteApi24VolumesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteApi24VolumesOK creates a DeleteApi24VolumesOK with default headers values
func NewDeleteApi24VolumesOK() *DeleteApi24VolumesOK {
	return &DeleteApi24VolumesOK{}
}

/*DeleteApi24VolumesOK handles this case with default header values.

OK
*/
type DeleteApi24VolumesOK struct {
}

func (o *DeleteApi24VolumesOK) Error() string {
	return fmt.Sprintf("[DELETE /api/2.4/volumes][%d] deleteApi24VolumesOK ", 200)
}

func (o *DeleteApi24VolumesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
