// Code generated by go-swagger; DO NOT EDIT.

package volumes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PureStorage-OpenConnect/terraform-provider-cbs/cbs/internal/array/faclient/2.4/models"
)

// DeleteAPI24VolumesTagsReader is a Reader for the DeleteAPI24VolumesTags structure.
type DeleteAPI24VolumesTagsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPI24VolumesTagsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteApi24VolumesTagsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteApi24VolumesTagsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteApi24VolumesTagsOK creates a DeleteApi24VolumesTagsOK with default headers values
func NewDeleteApi24VolumesTagsOK() *DeleteApi24VolumesTagsOK {
	return &DeleteApi24VolumesTagsOK{}
}

/*DeleteApi24VolumesTagsOK handles this case with default header values.

OK
*/
type DeleteApi24VolumesTagsOK struct {
}

func (o *DeleteApi24VolumesTagsOK) Error() string {
	return fmt.Sprintf("[DELETE /api/2.4/volumes/tags][%d] deleteApi24VolumesTagsOK ", 200)
}

func (o *DeleteApi24VolumesTagsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteApi24VolumesTagsBadRequest creates a DeleteApi24VolumesTagsBadRequest with default headers values
func NewDeleteApi24VolumesTagsBadRequest() *DeleteApi24VolumesTagsBadRequest {
	return &DeleteApi24VolumesTagsBadRequest{}
}

/*DeleteApi24VolumesTagsBadRequest handles this case with default header values.

BadRequest
*/
type DeleteApi24VolumesTagsBadRequest struct {
	Payload *models.Error
}

func (o *DeleteApi24VolumesTagsBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/2.4/volumes/tags][%d] deleteApi24VolumesTagsBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteApi24VolumesTagsBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteApi24VolumesTagsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
