// Code generated by go-swagger; DO NOT EDIT.

package volumes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PureStorage-OpenConnect/terraform-provider-cbs/cbs/internal/array/faclient/2.4/models"
)

// PostAPI24VolumesProtectionGroupsReader is a Reader for the PostAPI24VolumesProtectionGroups structure.
type PostAPI24VolumesProtectionGroupsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPI24VolumesProtectionGroupsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostApi24VolumesProtectionGroupsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostApi24VolumesProtectionGroupsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostApi24VolumesProtectionGroupsOK creates a PostApi24VolumesProtectionGroupsOK with default headers values
func NewPostApi24VolumesProtectionGroupsOK() *PostApi24VolumesProtectionGroupsOK {
	return &PostApi24VolumesProtectionGroupsOK{}
}

/*PostApi24VolumesProtectionGroupsOK handles this case with default header values.

OK
*/
type PostApi24VolumesProtectionGroupsOK struct {
	Payload *models.MemberNoIDAllResponse
}

func (o *PostApi24VolumesProtectionGroupsOK) Error() string {
	return fmt.Sprintf("[POST /api/2.4/volumes/protection-groups][%d] postApi24VolumesProtectionGroupsOK  %+v", 200, o.Payload)
}

func (o *PostApi24VolumesProtectionGroupsOK) GetPayload() *models.MemberNoIDAllResponse {
	return o.Payload
}

func (o *PostApi24VolumesProtectionGroupsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MemberNoIDAllResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostApi24VolumesProtectionGroupsBadRequest creates a PostApi24VolumesProtectionGroupsBadRequest with default headers values
func NewPostApi24VolumesProtectionGroupsBadRequest() *PostApi24VolumesProtectionGroupsBadRequest {
	return &PostApi24VolumesProtectionGroupsBadRequest{}
}

/*PostApi24VolumesProtectionGroupsBadRequest handles this case with default header values.

BadRequest
*/
type PostApi24VolumesProtectionGroupsBadRequest struct {
	Payload *models.Error
}

func (o *PostApi24VolumesProtectionGroupsBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/2.4/volumes/protection-groups][%d] postApi24VolumesProtectionGroupsBadRequest  %+v", 400, o.Payload)
}

func (o *PostApi24VolumesProtectionGroupsBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostApi24VolumesProtectionGroupsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
