// Code generated by go-swagger; DO NOT EDIT.

package arrays

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.dev.purestorage.com/FlashArray/terraform-provider-cbs/cbs/internal/array/faclient/2.4/models"
)

// GetAPI24ArraysReader is a Reader for the GetAPI24Arrays structure.
type GetAPI24ArraysReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPI24ArraysReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetApi24ArraysOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetApi24ArraysBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetApi24ArraysOK creates a GetApi24ArraysOK with default headers values
func NewGetApi24ArraysOK() *GetApi24ArraysOK {
	return &GetApi24ArraysOK{}
}

/*GetApi24ArraysOK handles this case with default header values.

OK
*/
type GetApi24ArraysOK struct {
	Payload *models.ArrayGetResponse
}

func (o *GetApi24ArraysOK) Error() string {
	return fmt.Sprintf("[GET /api/2.4/arrays][%d] getApi24ArraysOK  %+v", 200, o.Payload)
}

func (o *GetApi24ArraysOK) GetPayload() *models.ArrayGetResponse {
	return o.Payload
}

func (o *GetApi24ArraysOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ArrayGetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApi24ArraysBadRequest creates a GetApi24ArraysBadRequest with default headers values
func NewGetApi24ArraysBadRequest() *GetApi24ArraysBadRequest {
	return &GetApi24ArraysBadRequest{}
}

/*GetApi24ArraysBadRequest handles this case with default header values.

BadRequest
*/
type GetApi24ArraysBadRequest struct {
	Payload *models.Error
}

func (o *GetApi24ArraysBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/2.4/arrays][%d] getApi24ArraysBadRequest  %+v", 400, o.Payload)
}

func (o *GetApi24ArraysBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetApi24ArraysBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
