// Code generated by go-swagger; DO NOT EDIT.

package syslog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.dev.purestorage.com/FlashArray/terraform-provider-cbs/cbs/internal/faclient/2.4/models"
)

// PatchAPI24SyslogServersReader is a Reader for the PatchAPI24SyslogServers structure.
type PatchAPI24SyslogServersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchAPI24SyslogServersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchApi24SyslogServersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPatchApi24SyslogServersOK creates a PatchApi24SyslogServersOK with default headers values
func NewPatchApi24SyslogServersOK() *PatchApi24SyslogServersOK {
	return &PatchApi24SyslogServersOK{}
}

/*PatchApi24SyslogServersOK handles this case with default header values.

Displays the newly updated syslog server.
*/
type PatchApi24SyslogServersOK struct {
	Payload *models.SyslogServerResponse
}

func (o *PatchApi24SyslogServersOK) Error() string {
	return fmt.Sprintf("[PATCH /api/2.4/syslog-servers][%d] patchApi24SyslogServersOK  %+v", 200, o.Payload)
}

func (o *PatchApi24SyslogServersOK) GetPayload() *models.SyslogServerResponse {
	return o.Payload
}

func (o *PatchApi24SyslogServersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SyslogServerResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
