// Code generated by go-swagger; DO NOT EDIT.

package directories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteAPI24DirectoriesPoliciesSnapshotParams creates a new DeleteAPI24DirectoriesPoliciesSnapshotParams object
// with the default values initialized.
func NewDeleteAPI24DirectoriesPoliciesSnapshotParams() *DeleteAPI24DirectoriesPoliciesSnapshotParams {
	var ()
	return &DeleteAPI24DirectoriesPoliciesSnapshotParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPI24DirectoriesPoliciesSnapshotParamsWithTimeout creates a new DeleteAPI24DirectoriesPoliciesSnapshotParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAPI24DirectoriesPoliciesSnapshotParamsWithTimeout(timeout time.Duration) *DeleteAPI24DirectoriesPoliciesSnapshotParams {
	var ()
	return &DeleteAPI24DirectoriesPoliciesSnapshotParams{

		timeout: timeout,
	}
}

// NewDeleteAPI24DirectoriesPoliciesSnapshotParamsWithContext creates a new DeleteAPI24DirectoriesPoliciesSnapshotParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAPI24DirectoriesPoliciesSnapshotParamsWithContext(ctx context.Context) *DeleteAPI24DirectoriesPoliciesSnapshotParams {
	var ()
	return &DeleteAPI24DirectoriesPoliciesSnapshotParams{

		Context: ctx,
	}
}

// NewDeleteAPI24DirectoriesPoliciesSnapshotParamsWithHTTPClient creates a new DeleteAPI24DirectoriesPoliciesSnapshotParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAPI24DirectoriesPoliciesSnapshotParamsWithHTTPClient(client *http.Client) *DeleteAPI24DirectoriesPoliciesSnapshotParams {
	var ()
	return &DeleteAPI24DirectoriesPoliciesSnapshotParams{
		HTTPClient: client,
	}
}

/*DeleteAPI24DirectoriesPoliciesSnapshotParams contains all the parameters to send to the API endpoint
for the delete API 24 directories policies snapshot operation typically these are written to a http.Request
*/
type DeleteAPI24DirectoriesPoliciesSnapshotParams struct {

	/*Authorization
	  Access token (in JWT format) required to use any API endpoint (except `/oauth2`, `/login`, and `/logout`)

	*/
	Authorization *string
	/*XRequestID
	  Supplied by client during request or generated by server.

	*/
	XRequestID *string
	/*MemberIds
	  Performs the operation on the unique member IDs specified. Enter multiple member IDs in comma-separated format. The `member_ids` and `member_names` parameters cannot be provided together.

	*/
	MemberIds []string
	/*MemberNames
	  Performs the operation on the unique member name specified. Examples of members include volumes, hosts, host groups, and directories. Enter multiple names in comma-separated format. For example, `vol01,vol02`.

	*/
	MemberNames []string
	/*PolicyIds
	  Performs the operation on the unique policy IDs specified. Enter multiple policy IDs in comma-separated format. The `policy_ids` and `policy_names` parameters cannot be provided together.

	*/
	PolicyIds []string
	/*PolicyNames
	  Performs the operation on the policy names specified. Enter multiple policy names in comma-separated format. For example, `name01,name02`.

	*/
	PolicyNames []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete API 24 directories policies snapshot params
func (o *DeleteAPI24DirectoriesPoliciesSnapshotParams) WithTimeout(timeout time.Duration) *DeleteAPI24DirectoriesPoliciesSnapshotParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API 24 directories policies snapshot params
func (o *DeleteAPI24DirectoriesPoliciesSnapshotParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API 24 directories policies snapshot params
func (o *DeleteAPI24DirectoriesPoliciesSnapshotParams) WithContext(ctx context.Context) *DeleteAPI24DirectoriesPoliciesSnapshotParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API 24 directories policies snapshot params
func (o *DeleteAPI24DirectoriesPoliciesSnapshotParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API 24 directories policies snapshot params
func (o *DeleteAPI24DirectoriesPoliciesSnapshotParams) WithHTTPClient(client *http.Client) *DeleteAPI24DirectoriesPoliciesSnapshotParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API 24 directories policies snapshot params
func (o *DeleteAPI24DirectoriesPoliciesSnapshotParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the delete API 24 directories policies snapshot params
func (o *DeleteAPI24DirectoriesPoliciesSnapshotParams) WithAuthorization(authorization *string) *DeleteAPI24DirectoriesPoliciesSnapshotParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the delete API 24 directories policies snapshot params
func (o *DeleteAPI24DirectoriesPoliciesSnapshotParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithXRequestID adds the xRequestID to the delete API 24 directories policies snapshot params
func (o *DeleteAPI24DirectoriesPoliciesSnapshotParams) WithXRequestID(xRequestID *string) *DeleteAPI24DirectoriesPoliciesSnapshotParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the delete API 24 directories policies snapshot params
func (o *DeleteAPI24DirectoriesPoliciesSnapshotParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithMemberIds adds the memberIds to the delete API 24 directories policies snapshot params
func (o *DeleteAPI24DirectoriesPoliciesSnapshotParams) WithMemberIds(memberIds []string) *DeleteAPI24DirectoriesPoliciesSnapshotParams {
	o.SetMemberIds(memberIds)
	return o
}

// SetMemberIds adds the memberIds to the delete API 24 directories policies snapshot params
func (o *DeleteAPI24DirectoriesPoliciesSnapshotParams) SetMemberIds(memberIds []string) {
	o.MemberIds = memberIds
}

// WithMemberNames adds the memberNames to the delete API 24 directories policies snapshot params
func (o *DeleteAPI24DirectoriesPoliciesSnapshotParams) WithMemberNames(memberNames []string) *DeleteAPI24DirectoriesPoliciesSnapshotParams {
	o.SetMemberNames(memberNames)
	return o
}

// SetMemberNames adds the memberNames to the delete API 24 directories policies snapshot params
func (o *DeleteAPI24DirectoriesPoliciesSnapshotParams) SetMemberNames(memberNames []string) {
	o.MemberNames = memberNames
}

// WithPolicyIds adds the policyIds to the delete API 24 directories policies snapshot params
func (o *DeleteAPI24DirectoriesPoliciesSnapshotParams) WithPolicyIds(policyIds []string) *DeleteAPI24DirectoriesPoliciesSnapshotParams {
	o.SetPolicyIds(policyIds)
	return o
}

// SetPolicyIds adds the policyIds to the delete API 24 directories policies snapshot params
func (o *DeleteAPI24DirectoriesPoliciesSnapshotParams) SetPolicyIds(policyIds []string) {
	o.PolicyIds = policyIds
}

// WithPolicyNames adds the policyNames to the delete API 24 directories policies snapshot params
func (o *DeleteAPI24DirectoriesPoliciesSnapshotParams) WithPolicyNames(policyNames []string) *DeleteAPI24DirectoriesPoliciesSnapshotParams {
	o.SetPolicyNames(policyNames)
	return o
}

// SetPolicyNames adds the policyNames to the delete API 24 directories policies snapshot params
func (o *DeleteAPI24DirectoriesPoliciesSnapshotParams) SetPolicyNames(policyNames []string) {
	o.PolicyNames = policyNames
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPI24DirectoriesPoliciesSnapshotParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}

	}

	if o.XRequestID != nil {

		// header param X-Request-ID
		if err := r.SetHeaderParam("X-Request-ID", *o.XRequestID); err != nil {
			return err
		}

	}

	valuesMemberIds := o.MemberIds

	joinedMemberIds := swag.JoinByFormat(valuesMemberIds, "csv")
	// query array param member_ids
	if err := r.SetQueryParam("member_ids", joinedMemberIds...); err != nil {
		return err
	}

	valuesMemberNames := o.MemberNames

	joinedMemberNames := swag.JoinByFormat(valuesMemberNames, "csv")
	// query array param member_names
	if err := r.SetQueryParam("member_names", joinedMemberNames...); err != nil {
		return err
	}

	valuesPolicyIds := o.PolicyIds

	joinedPolicyIds := swag.JoinByFormat(valuesPolicyIds, "csv")
	// query array param policy_ids
	if err := r.SetQueryParam("policy_ids", joinedPolicyIds...); err != nil {
		return err
	}

	valuesPolicyNames := o.PolicyNames

	joinedPolicyNames := swag.JoinByFormat(valuesPolicyNames, "csv")
	// query array param policy_names
	if err := r.SetQueryParam("policy_names", joinedPolicyNames...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
