// Code generated by go-swagger; DO NOT EDIT.

package directories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PureStorage-OpenConnect/terraform-provider-cbs/cbs/internal/array/faclient/2.4/models"
)

// PostAPI24DirectoriesPoliciesSmbReader is a Reader for the PostAPI24DirectoriesPoliciesSmb structure.
type PostAPI24DirectoriesPoliciesSmbReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPI24DirectoriesPoliciesSmbReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostApi24DirectoriesPoliciesSmbOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostApi24DirectoriesPoliciesSmbBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostApi24DirectoriesPoliciesSmbOK creates a PostApi24DirectoriesPoliciesSmbOK with default headers values
func NewPostApi24DirectoriesPoliciesSmbOK() *PostApi24DirectoriesPoliciesSmbOK {
	return &PostApi24DirectoriesPoliciesSmbOK{}
}

/*PostApi24DirectoriesPoliciesSmbOK handles this case with default header values.

OK
*/
type PostApi24DirectoriesPoliciesSmbOK struct {
	Payload *models.PolicyMemberExportResponse
}

func (o *PostApi24DirectoriesPoliciesSmbOK) Error() string {
	return fmt.Sprintf("[POST /api/2.4/directories/policies/smb][%d] postApi24DirectoriesPoliciesSmbOK  %+v", 200, o.Payload)
}

func (o *PostApi24DirectoriesPoliciesSmbOK) GetPayload() *models.PolicyMemberExportResponse {
	return o.Payload
}

func (o *PostApi24DirectoriesPoliciesSmbOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PolicyMemberExportResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostApi24DirectoriesPoliciesSmbBadRequest creates a PostApi24DirectoriesPoliciesSmbBadRequest with default headers values
func NewPostApi24DirectoriesPoliciesSmbBadRequest() *PostApi24DirectoriesPoliciesSmbBadRequest {
	return &PostApi24DirectoriesPoliciesSmbBadRequest{}
}

/*PostApi24DirectoriesPoliciesSmbBadRequest handles this case with default header values.

BadRequest
*/
type PostApi24DirectoriesPoliciesSmbBadRequest struct {
	Payload *models.Error
}

func (o *PostApi24DirectoriesPoliciesSmbBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/2.4/directories/policies/smb][%d] postApi24DirectoriesPoliciesSmbBadRequest  %+v", 400, o.Payload)
}

func (o *PostApi24DirectoriesPoliciesSmbBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostApi24DirectoriesPoliciesSmbBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
