// Code generated by go-swagger; DO NOT EDIT.

package active_directory

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PureStorage-OpenConnect/terraform-provider-cbs/cbs/internal/array/faclient/2.4/models"
)

// DeleteAPI24ActiveDirectoryReader is a Reader for the DeleteAPI24ActiveDirectory structure.
type DeleteAPI24ActiveDirectoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPI24ActiveDirectoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteApi24ActiveDirectoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteApi24ActiveDirectoryBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteApi24ActiveDirectoryOK creates a DeleteApi24ActiveDirectoryOK with default headers values
func NewDeleteApi24ActiveDirectoryOK() *DeleteApi24ActiveDirectoryOK {
	return &DeleteApi24ActiveDirectoryOK{}
}

/*DeleteApi24ActiveDirectoryOK handles this case with default header values.

OK
*/
type DeleteApi24ActiveDirectoryOK struct {
}

func (o *DeleteApi24ActiveDirectoryOK) Error() string {
	return fmt.Sprintf("[DELETE /api/2.4/active-directory][%d] deleteApi24ActiveDirectoryOK ", 200)
}

func (o *DeleteApi24ActiveDirectoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteApi24ActiveDirectoryBadRequest creates a DeleteApi24ActiveDirectoryBadRequest with default headers values
func NewDeleteApi24ActiveDirectoryBadRequest() *DeleteApi24ActiveDirectoryBadRequest {
	return &DeleteApi24ActiveDirectoryBadRequest{}
}

/*DeleteApi24ActiveDirectoryBadRequest handles this case with default header values.

BadRequest
*/
type DeleteApi24ActiveDirectoryBadRequest struct {
	Payload *models.Error
}

func (o *DeleteApi24ActiveDirectoryBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/2.4/active-directory][%d] deleteApi24ActiveDirectoryBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteApi24ActiveDirectoryBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteApi24ActiveDirectoryBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
