// Code generated by go-swagger; DO NOT EDIT.

package volume_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAPI24VolumeGroupsReader is a Reader for the DeleteAPI24VolumeGroups structure.
type DeleteAPI24VolumeGroupsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPI24VolumeGroupsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteApi24VolumeGroupsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteApi24VolumeGroupsOK creates a DeleteApi24VolumeGroupsOK with default headers values
func NewDeleteApi24VolumeGroupsOK() *DeleteApi24VolumeGroupsOK {
	return &DeleteApi24VolumeGroupsOK{}
}

/*DeleteApi24VolumeGroupsOK handles this case with default header values.

OK
*/
type DeleteApi24VolumeGroupsOK struct {
}

func (o *DeleteApi24VolumeGroupsOK) Error() string {
	return fmt.Sprintf("[DELETE /api/2.4/volume-groups][%d] deleteApi24VolumeGroupsOK ", 200)
}

func (o *DeleteApi24VolumeGroupsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
