// Code generated by go-swagger; DO NOT EDIT.

package volume_snapshots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.dev.purestorage.com/FlashArray/terraform-provider-cbs/cbs/internal/faclient/2.4/models"
)

// GetAPI24VolumeSnapshotsTransferReader is a Reader for the GetAPI24VolumeSnapshotsTransfer structure.
type GetAPI24VolumeSnapshotsTransferReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPI24VolumeSnapshotsTransferReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetApi24VolumeSnapshotsTransferOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetApi24VolumeSnapshotsTransferOK creates a GetApi24VolumeSnapshotsTransferOK with default headers values
func NewGetApi24VolumeSnapshotsTransferOK() *GetApi24VolumeSnapshotsTransferOK {
	return &GetApi24VolumeSnapshotsTransferOK{}
}

/*GetApi24VolumeSnapshotsTransferOK handles this case with default header values.

OK
*/
type GetApi24VolumeSnapshotsTransferOK struct {
	Payload *models.VolumeSnapshotTransferGetResponse
}

func (o *GetApi24VolumeSnapshotsTransferOK) Error() string {
	return fmt.Sprintf("[GET /api/2.4/volume-snapshots/transfer][%d] getApi24VolumeSnapshotsTransferOK  %+v", 200, o.Payload)
}

func (o *GetApi24VolumeSnapshotsTransferOK) GetPayload() *models.VolumeSnapshotTransferGetResponse {
	return o.Payload
}

func (o *GetApi24VolumeSnapshotsTransferOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VolumeSnapshotTransferGetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
