// Code generated by go-swagger; DO NOT EDIT.

package volume_snapshots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPI24VolumeSnapshotsTagsParams creates a new GetAPI24VolumeSnapshotsTagsParams object
// with the default values initialized.
func NewGetAPI24VolumeSnapshotsTagsParams() *GetAPI24VolumeSnapshotsTagsParams {
	var ()
	return &GetAPI24VolumeSnapshotsTagsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPI24VolumeSnapshotsTagsParamsWithTimeout creates a new GetAPI24VolumeSnapshotsTagsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPI24VolumeSnapshotsTagsParamsWithTimeout(timeout time.Duration) *GetAPI24VolumeSnapshotsTagsParams {
	var ()
	return &GetAPI24VolumeSnapshotsTagsParams{

		timeout: timeout,
	}
}

// NewGetAPI24VolumeSnapshotsTagsParamsWithContext creates a new GetAPI24VolumeSnapshotsTagsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPI24VolumeSnapshotsTagsParamsWithContext(ctx context.Context) *GetAPI24VolumeSnapshotsTagsParams {
	var ()
	return &GetAPI24VolumeSnapshotsTagsParams{

		Context: ctx,
	}
}

// NewGetAPI24VolumeSnapshotsTagsParamsWithHTTPClient creates a new GetAPI24VolumeSnapshotsTagsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPI24VolumeSnapshotsTagsParamsWithHTTPClient(client *http.Client) *GetAPI24VolumeSnapshotsTagsParams {
	var ()
	return &GetAPI24VolumeSnapshotsTagsParams{
		HTTPClient: client,
	}
}

/*GetAPI24VolumeSnapshotsTagsParams contains all the parameters to send to the API endpoint
for the get API 24 volume snapshots tags operation typically these are written to a http.Request
*/
type GetAPI24VolumeSnapshotsTagsParams struct {

	/*Authorization
	  Access token (in JWT format) required to use any API endpoint (except `/oauth2`, `/login`, and `/logout`)

	*/
	Authorization *string
	/*XRequestID
	  Supplied by client during request or generated by server.

	*/
	XRequestID *string
	/*ContinuationToken
	  A token used to retrieve the next page of data with some consistency guaranteed. The token is a Base64 encoded value. Set `continuation_token` to the system-generated token taken from the `x-next-token` header field of the response. A query has reached its last page when the response does not include a token. Pagination requires the `limit` and `continuation_token` query parameters.

	*/
	ContinuationToken *string
	/*Filter
	  Narrows down the results to only the response objects that satisfy the filter criteria.

	*/
	Filter *string
	/*Limit
	  Limits the size of the response to the specified number of objects on each page. To return the total number of resources, set `limit=0`. The total number of resources is returned as a `total_item_count` value. If the page size requested is larger than the system maximum limit, the server returns the maximum limit, disregarding the requested page size.

	*/
	Limit *int32
	/*Namespaces
	  A comma-separated list of namespaces.

	*/
	Namespaces []string
	/*Offset
	  The starting position based on the results of the query in relation to the full set of response objects returned.

	*/
	Offset *int32
	/*ResourceDestroyed
	  If set to `true`, returns only objects from destroyed resources. Returns an error if the name of a live resource is specified in the `resource_names` query parameter. If set to `false`, returns only objects from live resources. Returns an error if the name of a destroyed resource is specified in the `resource_names` query parameter.

	*/
	ResourceDestroyed *bool
	/*ResourceIds
	  A comma-separated list of resource IDs. The `resource_ids` and `resource_names` parameters cannot be provided together.

	*/
	ResourceIds []string
	/*ResourceNames
	  A comma-separated list of resource names. The `resource_ids` and `resource_names` parameters cannot be provided together.

	*/
	ResourceNames []string
	/*Sort
	  Returns the response objects in the order specified. Set `sort` to the name in the response by which to sort. Sorting can be performed on any of the names in the response, and the objects can be sorted in ascending or descending order. By default, the response objects are sorted in ascending order. To sort in descending order, append the minus sign (`-`) to the name. A single request can be sorted on multiple objects. For example, you can sort all volumes from largest to smallest volume size, and then sort volumes of the same size in ascending order by volume name. To sort on multiple names, list the names as comma-separated values.

	*/
	Sort []string
	/*TotalItemCount
	  If set to `true`, the `total_item_count` matching the specified query parameters is calculated and returned in the response. If set to `false`, the `total_item_count` is `null` in the response. This may speed up queries where the `total_item_count` is large. If not specified, defaults to `false`.

	*/
	TotalItemCount *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) WithTimeout(timeout time.Duration) *GetAPI24VolumeSnapshotsTagsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) WithContext(ctx context.Context) *GetAPI24VolumeSnapshotsTagsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) WithHTTPClient(client *http.Client) *GetAPI24VolumeSnapshotsTagsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) WithAuthorization(authorization *string) *GetAPI24VolumeSnapshotsTagsParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithXRequestID adds the xRequestID to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) WithXRequestID(xRequestID *string) *GetAPI24VolumeSnapshotsTagsParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithContinuationToken adds the continuationToken to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) WithContinuationToken(continuationToken *string) *GetAPI24VolumeSnapshotsTagsParams {
	o.SetContinuationToken(continuationToken)
	return o
}

// SetContinuationToken adds the continuationToken to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) SetContinuationToken(continuationToken *string) {
	o.ContinuationToken = continuationToken
}

// WithFilter adds the filter to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) WithFilter(filter *string) *GetAPI24VolumeSnapshotsTagsParams {
	o.SetFilter(filter)
	return o
}

// SetFilter adds the filter to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) SetFilter(filter *string) {
	o.Filter = filter
}

// WithLimit adds the limit to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) WithLimit(limit *int32) *GetAPI24VolumeSnapshotsTagsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithNamespaces adds the namespaces to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) WithNamespaces(namespaces []string) *GetAPI24VolumeSnapshotsTagsParams {
	o.SetNamespaces(namespaces)
	return o
}

// SetNamespaces adds the namespaces to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) SetNamespaces(namespaces []string) {
	o.Namespaces = namespaces
}

// WithOffset adds the offset to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) WithOffset(offset *int32) *GetAPI24VolumeSnapshotsTagsParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) SetOffset(offset *int32) {
	o.Offset = offset
}

// WithResourceDestroyed adds the resourceDestroyed to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) WithResourceDestroyed(resourceDestroyed *bool) *GetAPI24VolumeSnapshotsTagsParams {
	o.SetResourceDestroyed(resourceDestroyed)
	return o
}

// SetResourceDestroyed adds the resourceDestroyed to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) SetResourceDestroyed(resourceDestroyed *bool) {
	o.ResourceDestroyed = resourceDestroyed
}

// WithResourceIds adds the resourceIds to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) WithResourceIds(resourceIds []string) *GetAPI24VolumeSnapshotsTagsParams {
	o.SetResourceIds(resourceIds)
	return o
}

// SetResourceIds adds the resourceIds to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) SetResourceIds(resourceIds []string) {
	o.ResourceIds = resourceIds
}

// WithResourceNames adds the resourceNames to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) WithResourceNames(resourceNames []string) *GetAPI24VolumeSnapshotsTagsParams {
	o.SetResourceNames(resourceNames)
	return o
}

// SetResourceNames adds the resourceNames to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) SetResourceNames(resourceNames []string) {
	o.ResourceNames = resourceNames
}

// WithSort adds the sort to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) WithSort(sort []string) *GetAPI24VolumeSnapshotsTagsParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) SetSort(sort []string) {
	o.Sort = sort
}

// WithTotalItemCount adds the totalItemCount to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) WithTotalItemCount(totalItemCount *bool) *GetAPI24VolumeSnapshotsTagsParams {
	o.SetTotalItemCount(totalItemCount)
	return o
}

// SetTotalItemCount adds the totalItemCount to the get API 24 volume snapshots tags params
func (o *GetAPI24VolumeSnapshotsTagsParams) SetTotalItemCount(totalItemCount *bool) {
	o.TotalItemCount = totalItemCount
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPI24VolumeSnapshotsTagsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}

	}

	if o.XRequestID != nil {

		// header param X-Request-ID
		if err := r.SetHeaderParam("X-Request-ID", *o.XRequestID); err != nil {
			return err
		}

	}

	if o.ContinuationToken != nil {

		// query param continuation_token
		var qrContinuationToken string
		if o.ContinuationToken != nil {
			qrContinuationToken = *o.ContinuationToken
		}
		qContinuationToken := qrContinuationToken
		if qContinuationToken != "" {

			if err := r.SetQueryParam("continuation_token", qContinuationToken); err != nil {
				return err
			}
		}

	}

	if o.Filter != nil {

		// query param filter
		var qrFilter string
		if o.Filter != nil {
			qrFilter = *o.Filter
		}
		qFilter := qrFilter
		if qFilter != "" {

			if err := r.SetQueryParam("filter", qFilter); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int32
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	valuesNamespaces := o.Namespaces

	joinedNamespaces := swag.JoinByFormat(valuesNamespaces, "csv")
	// query array param namespaces
	if err := r.SetQueryParam("namespaces", joinedNamespaces...); err != nil {
		return err
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int32
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt32(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.ResourceDestroyed != nil {

		// query param resource_destroyed
		var qrResourceDestroyed bool
		if o.ResourceDestroyed != nil {
			qrResourceDestroyed = *o.ResourceDestroyed
		}
		qResourceDestroyed := swag.FormatBool(qrResourceDestroyed)
		if qResourceDestroyed != "" {

			if err := r.SetQueryParam("resource_destroyed", qResourceDestroyed); err != nil {
				return err
			}
		}

	}

	valuesResourceIds := o.ResourceIds

	joinedResourceIds := swag.JoinByFormat(valuesResourceIds, "csv")
	// query array param resource_ids
	if err := r.SetQueryParam("resource_ids", joinedResourceIds...); err != nil {
		return err
	}

	valuesResourceNames := o.ResourceNames

	joinedResourceNames := swag.JoinByFormat(valuesResourceNames, "csv")
	// query array param resource_names
	if err := r.SetQueryParam("resource_names", joinedResourceNames...); err != nil {
		return err
	}

	valuesSort := o.Sort

	joinedSort := swag.JoinByFormat(valuesSort, "csv")
	// query array param sort
	if err := r.SetQueryParam("sort", joinedSort...); err != nil {
		return err
	}

	if o.TotalItemCount != nil {

		// query param total_item_count
		var qrTotalItemCount bool
		if o.TotalItemCount != nil {
			qrTotalItemCount = *o.TotalItemCount
		}
		qTotalItemCount := swag.FormatBool(qrTotalItemCount)
		if qTotalItemCount != "" {

			if err := r.SetQueryParam("total_item_count", qTotalItemCount); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
