// Code generated by go-swagger; DO NOT EDIT.

package volume_snapshots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.dev.purestorage.com/FlashArray/terraform-provider-cbs/cbs/internal/faclient/2.4/models"
)

// PostAPI24VolumeSnapshotsReader is a Reader for the PostAPI24VolumeSnapshots structure.
type PostAPI24VolumeSnapshotsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPI24VolumeSnapshotsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostApi24VolumeSnapshotsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostApi24VolumeSnapshotsOK creates a PostApi24VolumeSnapshotsOK with default headers values
func NewPostApi24VolumeSnapshotsOK() *PostApi24VolumeSnapshotsOK {
	return &PostApi24VolumeSnapshotsOK{}
}

/*PostApi24VolumeSnapshotsOK handles this case with default header values.

OK
*/
type PostApi24VolumeSnapshotsOK struct {
	Payload *models.VolumeSnapshotResponse
}

func (o *PostApi24VolumeSnapshotsOK) Error() string {
	return fmt.Sprintf("[POST /api/2.4/volume-snapshots][%d] postApi24VolumeSnapshotsOK  %+v", 200, o.Payload)
}

func (o *PostApi24VolumeSnapshotsOK) GetPayload() *models.VolumeSnapshotResponse {
	return o.Payload
}

func (o *PostApi24VolumeSnapshotsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VolumeSnapshotResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
