// Code generated by go-swagger; DO NOT EDIT.

package policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAPI24PoliciesSnapshotReader is a Reader for the DeleteAPI24PoliciesSnapshot structure.
type DeleteAPI24PoliciesSnapshotReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPI24PoliciesSnapshotReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteApi24PoliciesSnapshotOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteApi24PoliciesSnapshotOK creates a DeleteApi24PoliciesSnapshotOK with default headers values
func NewDeleteApi24PoliciesSnapshotOK() *DeleteApi24PoliciesSnapshotOK {
	return &DeleteApi24PoliciesSnapshotOK{}
}

/*DeleteApi24PoliciesSnapshotOK handles this case with default header values.

OK
*/
type DeleteApi24PoliciesSnapshotOK struct {
}

func (o *DeleteApi24PoliciesSnapshotOK) Error() string {
	return fmt.Sprintf("[DELETE /api/2.4/policies/snapshot][%d] deleteApi24PoliciesSnapshotOK ", 200)
}

func (o *DeleteApi24PoliciesSnapshotOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
