// Code generated by go-swagger; DO NOT EDIT.

package policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.dev.purestorage.com/FlashArray/terraform-provider-cbs/cbs/internal/faclient/2.4/models"
)

// GetAPI24PoliciesSnapshotReader is a Reader for the GetAPI24PoliciesSnapshot structure.
type GetAPI24PoliciesSnapshotReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPI24PoliciesSnapshotReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetApi24PoliciesSnapshotOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetApi24PoliciesSnapshotOK creates a GetApi24PoliciesSnapshotOK with default headers values
func NewGetApi24PoliciesSnapshotOK() *GetApi24PoliciesSnapshotOK {
	return &GetApi24PoliciesSnapshotOK{}
}

/*GetApi24PoliciesSnapshotOK handles this case with default header values.

OK
*/
type GetApi24PoliciesSnapshotOK struct {
	Payload *models.PolicyGetResponse
}

func (o *GetApi24PoliciesSnapshotOK) Error() string {
	return fmt.Sprintf("[GET /api/2.4/policies/snapshot][%d] getApi24PoliciesSnapshotOK  %+v", 200, o.Payload)
}

func (o *GetApi24PoliciesSnapshotOK) GetPayload() *models.PolicyGetResponse {
	return o.Payload
}

func (o *GetApi24PoliciesSnapshotOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PolicyGetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
