// Code generated by go-swagger; DO NOT EDIT.

package policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.dev.purestorage.com/FlashArray/terraform-provider-cbs/cbs/internal/faclient/2.4/models"
)

// GetAPI24PoliciesNfsClientRulesReader is a Reader for the GetAPI24PoliciesNfsClientRules structure.
type GetAPI24PoliciesNfsClientRulesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPI24PoliciesNfsClientRulesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetApi24PoliciesNfsClientRulesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetApi24PoliciesNfsClientRulesOK creates a GetApi24PoliciesNfsClientRulesOK with default headers values
func NewGetApi24PoliciesNfsClientRulesOK() *GetApi24PoliciesNfsClientRulesOK {
	return &GetApi24PoliciesNfsClientRulesOK{}
}

/*GetApi24PoliciesNfsClientRulesOK handles this case with default header values.

OK
*/
type GetApi24PoliciesNfsClientRulesOK struct {
	Payload *models.PolicyRuleNfsClientGetResponse
}

func (o *GetApi24PoliciesNfsClientRulesOK) Error() string {
	return fmt.Sprintf("[GET /api/2.4/policies/nfs/client-rules][%d] getApi24PoliciesNfsClientRulesOK  %+v", 200, o.Payload)
}

func (o *GetApi24PoliciesNfsClientRulesOK) GetPayload() *models.PolicyRuleNfsClientGetResponse {
	return o.Payload
}

func (o *GetApi24PoliciesNfsClientRulesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PolicyRuleNfsClientGetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
