// Code generated by go-swagger; DO NOT EDIT.

package policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.dev.purestorage.com/FlashArray/terraform-provider-cbs/cbs/internal/faclient/2.4/models"
)

// PatchAPI24PoliciesSmbReader is a Reader for the PatchAPI24PoliciesSmb structure.
type PatchAPI24PoliciesSmbReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchAPI24PoliciesSmbReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchApi24PoliciesSmbOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPatchApi24PoliciesSmbOK creates a PatchApi24PoliciesSmbOK with default headers values
func NewPatchApi24PoliciesSmbOK() *PatchApi24PoliciesSmbOK {
	return &PatchApi24PoliciesSmbOK{}
}

/*PatchApi24PoliciesSmbOK handles this case with default header values.

OK
*/
type PatchApi24PoliciesSmbOK struct {
	Payload *models.PolicySmbResponse
}

func (o *PatchApi24PoliciesSmbOK) Error() string {
	return fmt.Sprintf("[PATCH /api/2.4/policies/smb][%d] patchApi24PoliciesSmbOK  %+v", 200, o.Payload)
}

func (o *PatchApi24PoliciesSmbOK) GetPayload() *models.PolicySmbResponse {
	return o.Payload
}

func (o *PatchApi24PoliciesSmbOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PolicySmbResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
