// Code generated by go-swagger; DO NOT EDIT.

package policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.dev.purestorage.com/FlashArray/terraform-provider-cbs/cbs/internal/faclient/2.4/models"
)

// NewPostAPI24PoliciesNfsParams creates a new PostAPI24PoliciesNfsParams object
// with the default values initialized.
func NewPostAPI24PoliciesNfsParams() *PostAPI24PoliciesNfsParams {
	var ()
	return &PostAPI24PoliciesNfsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPI24PoliciesNfsParamsWithTimeout creates a new PostAPI24PoliciesNfsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAPI24PoliciesNfsParamsWithTimeout(timeout time.Duration) *PostAPI24PoliciesNfsParams {
	var ()
	return &PostAPI24PoliciesNfsParams{

		timeout: timeout,
	}
}

// NewPostAPI24PoliciesNfsParamsWithContext creates a new PostAPI24PoliciesNfsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAPI24PoliciesNfsParamsWithContext(ctx context.Context) *PostAPI24PoliciesNfsParams {
	var ()
	return &PostAPI24PoliciesNfsParams{

		Context: ctx,
	}
}

// NewPostAPI24PoliciesNfsParamsWithHTTPClient creates a new PostAPI24PoliciesNfsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAPI24PoliciesNfsParamsWithHTTPClient(client *http.Client) *PostAPI24PoliciesNfsParams {
	var ()
	return &PostAPI24PoliciesNfsParams{
		HTTPClient: client,
	}
}

/*PostAPI24PoliciesNfsParams contains all the parameters to send to the API endpoint
for the post API 24 policies nfs operation typically these are written to a http.Request
*/
type PostAPI24PoliciesNfsParams struct {

	/*Authorization
	  Access token (in JWT format) required to use any API endpoint (except `/oauth2`, `/login`, and `/logout`)

	*/
	Authorization *string
	/*XRequestID
	  Supplied by client during request or generated by server.

	*/
	XRequestID *string
	/*Names
	  Performs the operation on the unique name specified. Enter multiple names in comma-separated format. For example, `name01,name02`.

	*/
	Names []string
	/*Policy*/
	Policy *models.PolicyPost

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post API 24 policies nfs params
func (o *PostAPI24PoliciesNfsParams) WithTimeout(timeout time.Duration) *PostAPI24PoliciesNfsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API 24 policies nfs params
func (o *PostAPI24PoliciesNfsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API 24 policies nfs params
func (o *PostAPI24PoliciesNfsParams) WithContext(ctx context.Context) *PostAPI24PoliciesNfsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API 24 policies nfs params
func (o *PostAPI24PoliciesNfsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API 24 policies nfs params
func (o *PostAPI24PoliciesNfsParams) WithHTTPClient(client *http.Client) *PostAPI24PoliciesNfsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API 24 policies nfs params
func (o *PostAPI24PoliciesNfsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the post API 24 policies nfs params
func (o *PostAPI24PoliciesNfsParams) WithAuthorization(authorization *string) *PostAPI24PoliciesNfsParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the post API 24 policies nfs params
func (o *PostAPI24PoliciesNfsParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithXRequestID adds the xRequestID to the post API 24 policies nfs params
func (o *PostAPI24PoliciesNfsParams) WithXRequestID(xRequestID *string) *PostAPI24PoliciesNfsParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the post API 24 policies nfs params
func (o *PostAPI24PoliciesNfsParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithNames adds the names to the post API 24 policies nfs params
func (o *PostAPI24PoliciesNfsParams) WithNames(names []string) *PostAPI24PoliciesNfsParams {
	o.SetNames(names)
	return o
}

// SetNames adds the names to the post API 24 policies nfs params
func (o *PostAPI24PoliciesNfsParams) SetNames(names []string) {
	o.Names = names
}

// WithPolicy adds the policy to the post API 24 policies nfs params
func (o *PostAPI24PoliciesNfsParams) WithPolicy(policy *models.PolicyPost) *PostAPI24PoliciesNfsParams {
	o.SetPolicy(policy)
	return o
}

// SetPolicy adds the policy to the post API 24 policies nfs params
func (o *PostAPI24PoliciesNfsParams) SetPolicy(policy *models.PolicyPost) {
	o.Policy = policy
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPI24PoliciesNfsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}

	}

	if o.XRequestID != nil {

		// header param X-Request-ID
		if err := r.SetHeaderParam("X-Request-ID", *o.XRequestID); err != nil {
			return err
		}

	}

	valuesNames := o.Names

	joinedNames := swag.JoinByFormat(valuesNames, "csv")
	// query array param names
	if err := r.SetQueryParam("names", joinedNames...); err != nil {
		return err
	}

	if o.Policy != nil {
		if err := r.SetBodyParam(o.Policy); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
