// Code generated by go-swagger; DO NOT EDIT.

package policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.dev.purestorage.com/FlashArray/terraform-provider-cbs/cbs/internal/faclient/2.4/models"
)

// PostAPI24PoliciesSnapshotMembersReader is a Reader for the PostAPI24PoliciesSnapshotMembers structure.
type PostAPI24PoliciesSnapshotMembersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPI24PoliciesSnapshotMembersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostApi24PoliciesSnapshotMembersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostApi24PoliciesSnapshotMembersOK creates a PostApi24PoliciesSnapshotMembersOK with default headers values
func NewPostApi24PoliciesSnapshotMembersOK() *PostApi24PoliciesSnapshotMembersOK {
	return &PostApi24PoliciesSnapshotMembersOK{}
}

/*PostApi24PoliciesSnapshotMembersOK handles this case with default header values.

OK
*/
type PostApi24PoliciesSnapshotMembersOK struct {
	Payload *models.PolicyMemberResponse
}

func (o *PostApi24PoliciesSnapshotMembersOK) Error() string {
	return fmt.Sprintf("[POST /api/2.4/policies/snapshot/members][%d] postApi24PoliciesSnapshotMembersOK  %+v", 200, o.Payload)
}

func (o *PostApi24PoliciesSnapshotMembersOK) GetPayload() *models.PolicyMemberResponse {
	return o.Payload
}

func (o *PostApi24PoliciesSnapshotMembersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PolicyMemberResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
