// Code generated by go-swagger; DO NOT EDIT.

package snmp_managers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAPI24SNMPManagersReader is a Reader for the DeleteAPI24SNMPManagers structure.
type DeleteAPI24SNMPManagersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPI24SNMPManagersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteApi24SNMPManagersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteApi24SNMPManagersOK creates a DeleteApi24SNMPManagersOK with default headers values
func NewDeleteApi24SNMPManagersOK() *DeleteApi24SNMPManagersOK {
	return &DeleteApi24SNMPManagersOK{}
}

/*DeleteApi24SNMPManagersOK handles this case with default header values.

OK
*/
type DeleteApi24SNMPManagersOK struct {
}

func (o *DeleteApi24SNMPManagersOK) Error() string {
	return fmt.Sprintf("[DELETE /api/2.4/snmp-managers][%d] deleteApi24SnmpManagersOK ", 200)
}

func (o *DeleteApi24SNMPManagersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
