// Code generated by go-swagger; DO NOT EDIT.

package directories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAPI24DirectoriesReader is a Reader for the DeleteAPI24Directories structure.
type DeleteAPI24DirectoriesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPI24DirectoriesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteApi24DirectoriesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteApi24DirectoriesOK creates a DeleteApi24DirectoriesOK with default headers values
func NewDeleteApi24DirectoriesOK() *DeleteApi24DirectoriesOK {
	return &DeleteApi24DirectoriesOK{}
}

/*DeleteApi24DirectoriesOK handles this case with default header values.

OK
*/
type DeleteApi24DirectoriesOK struct {
}

func (o *DeleteApi24DirectoriesOK) Error() string {
	return fmt.Sprintf("[DELETE /api/2.4/directories][%d] deleteApi24DirectoriesOK ", 200)
}

func (o *DeleteApi24DirectoriesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
