// Code generated by go-swagger; DO NOT EDIT.

package software

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.dev.purestorage.com/FlashArray/terraform-provider-cbs/cbs/internal/faclient/2.4/models"
)

// NewPostAPI24SoftwareInstallationsParams creates a new PostAPI24SoftwareInstallationsParams object
// with the default values initialized.
func NewPostAPI24SoftwareInstallationsParams() *PostAPI24SoftwareInstallationsParams {
	var ()
	return &PostAPI24SoftwareInstallationsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPI24SoftwareInstallationsParamsWithTimeout creates a new PostAPI24SoftwareInstallationsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAPI24SoftwareInstallationsParamsWithTimeout(timeout time.Duration) *PostAPI24SoftwareInstallationsParams {
	var ()
	return &PostAPI24SoftwareInstallationsParams{

		timeout: timeout,
	}
}

// NewPostAPI24SoftwareInstallationsParamsWithContext creates a new PostAPI24SoftwareInstallationsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAPI24SoftwareInstallationsParamsWithContext(ctx context.Context) *PostAPI24SoftwareInstallationsParams {
	var ()
	return &PostAPI24SoftwareInstallationsParams{

		Context: ctx,
	}
}

// NewPostAPI24SoftwareInstallationsParamsWithHTTPClient creates a new PostAPI24SoftwareInstallationsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAPI24SoftwareInstallationsParamsWithHTTPClient(client *http.Client) *PostAPI24SoftwareInstallationsParams {
	var ()
	return &PostAPI24SoftwareInstallationsParams{
		HTTPClient: client,
	}
}

/*PostAPI24SoftwareInstallationsParams contains all the parameters to send to the API endpoint
for the post API 24 software installations operation typically these are written to a http.Request
*/
type PostAPI24SoftwareInstallationsParams struct {

	/*Authorization
	  Access token (in JWT format) required to use any API endpoint (except `/oauth2`, `/login`, and `/logout`)

	*/
	Authorization *string
	/*XRequestID
	  Supplied by client during request or generated by server.

	*/
	XRequestID *string
	/*SoftwareInstallations*/
	SoftwareInstallations *models.SoftwareInstallationPost
	/*SoftwareIds
	  A comma-separated list of software IDs.

	*/
	SoftwareIds []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post API 24 software installations params
func (o *PostAPI24SoftwareInstallationsParams) WithTimeout(timeout time.Duration) *PostAPI24SoftwareInstallationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API 24 software installations params
func (o *PostAPI24SoftwareInstallationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API 24 software installations params
func (o *PostAPI24SoftwareInstallationsParams) WithContext(ctx context.Context) *PostAPI24SoftwareInstallationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API 24 software installations params
func (o *PostAPI24SoftwareInstallationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API 24 software installations params
func (o *PostAPI24SoftwareInstallationsParams) WithHTTPClient(client *http.Client) *PostAPI24SoftwareInstallationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API 24 software installations params
func (o *PostAPI24SoftwareInstallationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the post API 24 software installations params
func (o *PostAPI24SoftwareInstallationsParams) WithAuthorization(authorization *string) *PostAPI24SoftwareInstallationsParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the post API 24 software installations params
func (o *PostAPI24SoftwareInstallationsParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithXRequestID adds the xRequestID to the post API 24 software installations params
func (o *PostAPI24SoftwareInstallationsParams) WithXRequestID(xRequestID *string) *PostAPI24SoftwareInstallationsParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the post API 24 software installations params
func (o *PostAPI24SoftwareInstallationsParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithSoftwareInstallations adds the softwareInstallations to the post API 24 software installations params
func (o *PostAPI24SoftwareInstallationsParams) WithSoftwareInstallations(softwareInstallations *models.SoftwareInstallationPost) *PostAPI24SoftwareInstallationsParams {
	o.SetSoftwareInstallations(softwareInstallations)
	return o
}

// SetSoftwareInstallations adds the softwareInstallations to the post API 24 software installations params
func (o *PostAPI24SoftwareInstallationsParams) SetSoftwareInstallations(softwareInstallations *models.SoftwareInstallationPost) {
	o.SoftwareInstallations = softwareInstallations
}

// WithSoftwareIds adds the softwareIds to the post API 24 software installations params
func (o *PostAPI24SoftwareInstallationsParams) WithSoftwareIds(softwareIds []string) *PostAPI24SoftwareInstallationsParams {
	o.SetSoftwareIds(softwareIds)
	return o
}

// SetSoftwareIds adds the softwareIds to the post API 24 software installations params
func (o *PostAPI24SoftwareInstallationsParams) SetSoftwareIds(softwareIds []string) {
	o.SoftwareIds = softwareIds
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPI24SoftwareInstallationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}

	}

	if o.XRequestID != nil {

		// header param X-Request-ID
		if err := r.SetHeaderParam("X-Request-ID", *o.XRequestID); err != nil {
			return err
		}

	}

	if o.SoftwareInstallations != nil {
		if err := r.SetBodyParam(o.SoftwareInstallations); err != nil {
			return err
		}
	}

	valuesSoftwareIds := o.SoftwareIds

	joinedSoftwareIds := swag.JoinByFormat(valuesSoftwareIds, "csv")
	// query array param software_ids
	if err := r.SetQueryParam("software_ids", joinedSoftwareIds...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
