// Code generated by go-swagger; DO NOT EDIT.

package alerts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new alerts API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for alerts API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetAPI24Alerts(params *GetAPI24AlertsParams) (*GetApi24AlertsOK, error)

	GetAPI24AlertsEvents(params *GetAPI24AlertsEventsParams) (*GetApi24AlertsEventsOK, error)

	PatchAPI24Alerts(params *PatchAPI24AlertsParams) (*PatchApi24AlertsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetAPI24Alerts lists alerts

  Displays a list of alerts.
*/
func (a *Client) GetAPI24Alerts(params *GetAPI24AlertsParams) (*GetApi24AlertsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAPI24AlertsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetAPI24Alerts",
		Method:             "GET",
		PathPattern:        "/api/2.4/alerts",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPI24AlertsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetApi24AlertsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPI24Alerts: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetAPI24AlertsEvents lists alert events

  Displays a list of alert events.
*/
func (a *Client) GetAPI24AlertsEvents(params *GetAPI24AlertsEventsParams) (*GetApi24AlertsEventsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAPI24AlertsEventsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetAPI24AlertsEvents",
		Method:             "GET",
		PathPattern:        "/api/2.4/alerts/events",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPI24AlertsEventsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetApi24AlertsEventsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPI24AlertsEvents: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PatchAPI24Alerts modifies flagged state

  Modifies one or more alerts and display updated information about these alerts.
*/
func (a *Client) PatchAPI24Alerts(params *PatchAPI24AlertsParams) (*PatchApi24AlertsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPatchAPI24AlertsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PatchAPI24Alerts",
		Method:             "PATCH",
		PathPattern:        "/api/2.4/alerts",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PatchAPI24AlertsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PatchApi24AlertsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PatchAPI24Alerts: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
