// Code generated by go-swagger; DO NOT EDIT.

package protection_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PureStorage-OpenConnect/terraform-provider-cbs/cbs/internal/array/faclient/2.4/models"
)

// GetAPI24ProtectionGroupsPerformanceReplicationByArrayReader is a Reader for the GetAPI24ProtectionGroupsPerformanceReplicationByArray structure.
type GetAPI24ProtectionGroupsPerformanceReplicationByArrayReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPI24ProtectionGroupsPerformanceReplicationByArrayReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetApi24ProtectionGroupsPerformanceReplicationByArrayOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetApi24ProtectionGroupsPerformanceReplicationByArrayBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetApi24ProtectionGroupsPerformanceReplicationByArrayOK creates a GetApi24ProtectionGroupsPerformanceReplicationByArrayOK with default headers values
func NewGetApi24ProtectionGroupsPerformanceReplicationByArrayOK() *GetApi24ProtectionGroupsPerformanceReplicationByArrayOK {
	return &GetApi24ProtectionGroupsPerformanceReplicationByArrayOK{}
}

/*GetApi24ProtectionGroupsPerformanceReplicationByArrayOK handles this case with default header values.

OK
*/
type GetApi24ProtectionGroupsPerformanceReplicationByArrayOK struct {
	Payload *models.ProtectionGroupPerformanceArrayResponse
}

func (o *GetApi24ProtectionGroupsPerformanceReplicationByArrayOK) Error() string {
	return fmt.Sprintf("[GET /api/2.4/protection-groups/performance/replication/by-array][%d] getApi24ProtectionGroupsPerformanceReplicationByArrayOK  %+v", 200, o.Payload)
}

func (o *GetApi24ProtectionGroupsPerformanceReplicationByArrayOK) GetPayload() *models.ProtectionGroupPerformanceArrayResponse {
	return o.Payload
}

func (o *GetApi24ProtectionGroupsPerformanceReplicationByArrayOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProtectionGroupPerformanceArrayResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApi24ProtectionGroupsPerformanceReplicationByArrayBadRequest creates a GetApi24ProtectionGroupsPerformanceReplicationByArrayBadRequest with default headers values
func NewGetApi24ProtectionGroupsPerformanceReplicationByArrayBadRequest() *GetApi24ProtectionGroupsPerformanceReplicationByArrayBadRequest {
	return &GetApi24ProtectionGroupsPerformanceReplicationByArrayBadRequest{}
}

/*GetApi24ProtectionGroupsPerformanceReplicationByArrayBadRequest handles this case with default header values.

BadRequest
*/
type GetApi24ProtectionGroupsPerformanceReplicationByArrayBadRequest struct {
	Payload *models.Error
}

func (o *GetApi24ProtectionGroupsPerformanceReplicationByArrayBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/2.4/protection-groups/performance/replication/by-array][%d] getApi24ProtectionGroupsPerformanceReplicationByArrayBadRequest  %+v", 400, o.Payload)
}

func (o *GetApi24ProtectionGroupsPerformanceReplicationByArrayBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetApi24ProtectionGroupsPerformanceReplicationByArrayBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
