// Code generated by go-swagger; DO NOT EDIT.

package hosts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAPI24HostsProtectionGroupsReader is a Reader for the DeleteAPI24HostsProtectionGroups structure.
type DeleteAPI24HostsProtectionGroupsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPI24HostsProtectionGroupsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteApi24HostsProtectionGroupsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteApi24HostsProtectionGroupsOK creates a DeleteApi24HostsProtectionGroupsOK with default headers values
func NewDeleteApi24HostsProtectionGroupsOK() *DeleteApi24HostsProtectionGroupsOK {
	return &DeleteApi24HostsProtectionGroupsOK{}
}

/*DeleteApi24HostsProtectionGroupsOK handles this case with default header values.

OK
*/
type DeleteApi24HostsProtectionGroupsOK struct {
}

func (o *DeleteApi24HostsProtectionGroupsOK) Error() string {
	return fmt.Sprintf("[DELETE /api/2.4/hosts/protection-groups][%d] deleteApi24HostsProtectionGroupsOK ", 200)
}

func (o *DeleteApi24HostsProtectionGroupsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
