// Code generated by go-swagger; DO NOT EDIT.

package support

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PureStorage-OpenConnect/terraform-provider-cbs/cbs/internal/array/faclient/2.4/models"
)

// GetAPI24SupportTestReader is a Reader for the GetAPI24SupportTest structure.
type GetAPI24SupportTestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPI24SupportTestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetApi24SupportTestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetApi24SupportTestBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetApi24SupportTestOK creates a GetApi24SupportTestOK with default headers values
func NewGetApi24SupportTestOK() *GetApi24SupportTestOK {
	return &GetApi24SupportTestOK{}
}

/*GetApi24SupportTestOK handles this case with default header values.

OK
*/
type GetApi24SupportTestOK struct {
	Payload *models.TestResultGetResponse
}

func (o *GetApi24SupportTestOK) Error() string {
	return fmt.Sprintf("[GET /api/2.4/support/test][%d] getApi24SupportTestOK  %+v", 200, o.Payload)
}

func (o *GetApi24SupportTestOK) GetPayload() *models.TestResultGetResponse {
	return o.Payload
}

func (o *GetApi24SupportTestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TestResultGetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApi24SupportTestBadRequest creates a GetApi24SupportTestBadRequest with default headers values
func NewGetApi24SupportTestBadRequest() *GetApi24SupportTestBadRequest {
	return &GetApi24SupportTestBadRequest{}
}

/*GetApi24SupportTestBadRequest handles this case with default header values.

BadRequest
*/
type GetApi24SupportTestBadRequest struct {
	Payload *models.Error
}

func (o *GetApi24SupportTestBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/2.4/support/test][%d] getApi24SupportTestBadRequest  %+v", 400, o.Payload)
}

func (o *GetApi24SupportTestBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetApi24SupportTestBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
