// Code generated by go-swagger; DO NOT EDIT.

package hosts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.dev.purestorage.com/FlashArray/terraform-provider-cbs/cbs/internal/array/faclient/2.4/models"
)

// DeleteAPI24HostsProtectionGroupsReader is a Reader for the DeleteAPI24HostsProtectionGroups structure.
type DeleteAPI24HostsProtectionGroupsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPI24HostsProtectionGroupsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteApi24HostsProtectionGroupsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteApi24HostsProtectionGroupsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteApi24HostsProtectionGroupsOK creates a DeleteApi24HostsProtectionGroupsOK with default headers values
func NewDeleteApi24HostsProtectionGroupsOK() *DeleteApi24HostsProtectionGroupsOK {
	return &DeleteApi24HostsProtectionGroupsOK{}
}

/*DeleteApi24HostsProtectionGroupsOK handles this case with default header values.

OK
*/
type DeleteApi24HostsProtectionGroupsOK struct {
}

func (o *DeleteApi24HostsProtectionGroupsOK) Error() string {
	return fmt.Sprintf("[DELETE /api/2.4/hosts/protection-groups][%d] deleteApi24HostsProtectionGroupsOK ", 200)
}

func (o *DeleteApi24HostsProtectionGroupsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteApi24HostsProtectionGroupsBadRequest creates a DeleteApi24HostsProtectionGroupsBadRequest with default headers values
func NewDeleteApi24HostsProtectionGroupsBadRequest() *DeleteApi24HostsProtectionGroupsBadRequest {
	return &DeleteApi24HostsProtectionGroupsBadRequest{}
}

/*DeleteApi24HostsProtectionGroupsBadRequest handles this case with default header values.

BadRequest
*/
type DeleteApi24HostsProtectionGroupsBadRequest struct {
	Payload *models.Error
}

func (o *DeleteApi24HostsProtectionGroupsBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/2.4/hosts/protection-groups][%d] deleteApi24HostsProtectionGroupsBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteApi24HostsProtectionGroupsBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteApi24HostsProtectionGroupsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
