// Code generated by go-swagger; DO NOT EDIT.

package hosts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteAPI24HostsParams creates a new DeleteAPI24HostsParams object
// with the default values initialized.
func NewDeleteAPI24HostsParams() *DeleteAPI24HostsParams {
	var ()
	return &DeleteAPI24HostsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPI24HostsParamsWithTimeout creates a new DeleteAPI24HostsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAPI24HostsParamsWithTimeout(timeout time.Duration) *DeleteAPI24HostsParams {
	var ()
	return &DeleteAPI24HostsParams{

		timeout: timeout,
	}
}

// NewDeleteAPI24HostsParamsWithContext creates a new DeleteAPI24HostsParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAPI24HostsParamsWithContext(ctx context.Context) *DeleteAPI24HostsParams {
	var ()
	return &DeleteAPI24HostsParams{

		Context: ctx,
	}
}

// NewDeleteAPI24HostsParamsWithHTTPClient creates a new DeleteAPI24HostsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAPI24HostsParamsWithHTTPClient(client *http.Client) *DeleteAPI24HostsParams {
	var ()
	return &DeleteAPI24HostsParams{
		HTTPClient: client,
	}
}

/*DeleteAPI24HostsParams contains all the parameters to send to the API endpoint
for the delete API 24 hosts operation typically these are written to a http.Request
*/
type DeleteAPI24HostsParams struct {

	/*Authorization
	  Access token (in JWT format) required to use any API endpoint (except `/oauth2`, `/login`, and `/logout`)

	*/
	Authorization *string
	/*XRequestID
	  Supplied by client during request or generated by server.

	*/
	XRequestID *string
	/*Names
	  Performs the operation on the unique name specified. Enter multiple names in comma-separated format. For example, `name01,name02`.

	*/
	Names []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete API 24 hosts params
func (o *DeleteAPI24HostsParams) WithTimeout(timeout time.Duration) *DeleteAPI24HostsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API 24 hosts params
func (o *DeleteAPI24HostsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API 24 hosts params
func (o *DeleteAPI24HostsParams) WithContext(ctx context.Context) *DeleteAPI24HostsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API 24 hosts params
func (o *DeleteAPI24HostsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API 24 hosts params
func (o *DeleteAPI24HostsParams) WithHTTPClient(client *http.Client) *DeleteAPI24HostsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API 24 hosts params
func (o *DeleteAPI24HostsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the delete API 24 hosts params
func (o *DeleteAPI24HostsParams) WithAuthorization(authorization *string) *DeleteAPI24HostsParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the delete API 24 hosts params
func (o *DeleteAPI24HostsParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithXRequestID adds the xRequestID to the delete API 24 hosts params
func (o *DeleteAPI24HostsParams) WithXRequestID(xRequestID *string) *DeleteAPI24HostsParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the delete API 24 hosts params
func (o *DeleteAPI24HostsParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithNames adds the names to the delete API 24 hosts params
func (o *DeleteAPI24HostsParams) WithNames(names []string) *DeleteAPI24HostsParams {
	o.SetNames(names)
	return o
}

// SetNames adds the names to the delete API 24 hosts params
func (o *DeleteAPI24HostsParams) SetNames(names []string) {
	o.Names = names
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPI24HostsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}

	}

	if o.XRequestID != nil {

		// header param X-Request-ID
		if err := r.SetHeaderParam("X-Request-ID", *o.XRequestID); err != nil {
			return err
		}

	}

	valuesNames := o.Names

	joinedNames := swag.JoinByFormat(valuesNames, "csv")
	// query array param names
	if err := r.SetQueryParam("names", joinedNames...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
