// Code generated by go-swagger; DO NOT EDIT.

package hosts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.dev.purestorage.com/FlashArray/terraform-provider-cbs/cbs/internal/array/faclient/2.4/models"
)

// GetAPI24HostsPerformanceBalanceReader is a Reader for the GetAPI24HostsPerformanceBalance structure.
type GetAPI24HostsPerformanceBalanceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPI24HostsPerformanceBalanceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetApi24HostsPerformanceBalanceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetApi24HostsPerformanceBalanceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetApi24HostsPerformanceBalanceOK creates a GetApi24HostsPerformanceBalanceOK with default headers values
func NewGetApi24HostsPerformanceBalanceOK() *GetApi24HostsPerformanceBalanceOK {
	return &GetApi24HostsPerformanceBalanceOK{}
}

/*GetApi24HostsPerformanceBalanceOK handles this case with default header values.

OK
*/
type GetApi24HostsPerformanceBalanceOK struct {
	Payload *models.HostPerformanceBalanceGetResponse
}

func (o *GetApi24HostsPerformanceBalanceOK) Error() string {
	return fmt.Sprintf("[GET /api/2.4/hosts/performance/balance][%d] getApi24HostsPerformanceBalanceOK  %+v", 200, o.Payload)
}

func (o *GetApi24HostsPerformanceBalanceOK) GetPayload() *models.HostPerformanceBalanceGetResponse {
	return o.Payload
}

func (o *GetApi24HostsPerformanceBalanceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HostPerformanceBalanceGetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApi24HostsPerformanceBalanceBadRequest creates a GetApi24HostsPerformanceBalanceBadRequest with default headers values
func NewGetApi24HostsPerformanceBalanceBadRequest() *GetApi24HostsPerformanceBalanceBadRequest {
	return &GetApi24HostsPerformanceBalanceBadRequest{}
}

/*GetApi24HostsPerformanceBalanceBadRequest handles this case with default header values.

BadRequest
*/
type GetApi24HostsPerformanceBalanceBadRequest struct {
	Payload *models.Error
}

func (o *GetApi24HostsPerformanceBalanceBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/2.4/hosts/performance/balance][%d] getApi24HostsPerformanceBalanceBadRequest  %+v", 400, o.Payload)
}

func (o *GetApi24HostsPerformanceBalanceBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetApi24HostsPerformanceBalanceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
