// Code generated by go-swagger; DO NOT EDIT.

package pod_replica_links

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.dev.purestorage.com/FlashArray/terraform-provider-cbs/cbs/internal/array/faclient/2.4/models"
)

// GetAPI24PodReplicaLinksPerformanceReplicationReader is a Reader for the GetAPI24PodReplicaLinksPerformanceReplication structure.
type GetAPI24PodReplicaLinksPerformanceReplicationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPI24PodReplicaLinksPerformanceReplicationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetApi24PodReplicaLinksPerformanceReplicationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetApi24PodReplicaLinksPerformanceReplicationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetApi24PodReplicaLinksPerformanceReplicationOK creates a GetApi24PodReplicaLinksPerformanceReplicationOK with default headers values
func NewGetApi24PodReplicaLinksPerformanceReplicationOK() *GetApi24PodReplicaLinksPerformanceReplicationOK {
	return &GetApi24PodReplicaLinksPerformanceReplicationOK{}
}

/*GetApi24PodReplicaLinksPerformanceReplicationOK handles this case with default header values.

OK
*/
type GetApi24PodReplicaLinksPerformanceReplicationOK struct {
	Payload *models.PodReplicaLinkPerformanceReplicationGetResponse
}

func (o *GetApi24PodReplicaLinksPerformanceReplicationOK) Error() string {
	return fmt.Sprintf("[GET /api/2.4/pod-replica-links/performance/replication][%d] getApi24PodReplicaLinksPerformanceReplicationOK  %+v", 200, o.Payload)
}

func (o *GetApi24PodReplicaLinksPerformanceReplicationOK) GetPayload() *models.PodReplicaLinkPerformanceReplicationGetResponse {
	return o.Payload
}

func (o *GetApi24PodReplicaLinksPerformanceReplicationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PodReplicaLinkPerformanceReplicationGetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApi24PodReplicaLinksPerformanceReplicationBadRequest creates a GetApi24PodReplicaLinksPerformanceReplicationBadRequest with default headers values
func NewGetApi24PodReplicaLinksPerformanceReplicationBadRequest() *GetApi24PodReplicaLinksPerformanceReplicationBadRequest {
	return &GetApi24PodReplicaLinksPerformanceReplicationBadRequest{}
}

/*GetApi24PodReplicaLinksPerformanceReplicationBadRequest handles this case with default header values.

BadRequest
*/
type GetApi24PodReplicaLinksPerformanceReplicationBadRequest struct {
	Payload *models.Error
}

func (o *GetApi24PodReplicaLinksPerformanceReplicationBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/2.4/pod-replica-links/performance/replication][%d] getApi24PodReplicaLinksPerformanceReplicationBadRequest  %+v", 400, o.Payload)
}

func (o *GetApi24PodReplicaLinksPerformanceReplicationBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetApi24PodReplicaLinksPerformanceReplicationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
