// Code generated by go-swagger; DO NOT EDIT.

package protection_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAPI24ProtectionGroupsVolumesReader is a Reader for the DeleteAPI24ProtectionGroupsVolumes structure.
type DeleteAPI24ProtectionGroupsVolumesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPI24ProtectionGroupsVolumesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteApi24ProtectionGroupsVolumesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteApi24ProtectionGroupsVolumesOK creates a DeleteApi24ProtectionGroupsVolumesOK with default headers values
func NewDeleteApi24ProtectionGroupsVolumesOK() *DeleteApi24ProtectionGroupsVolumesOK {
	return &DeleteApi24ProtectionGroupsVolumesOK{}
}

/*DeleteApi24ProtectionGroupsVolumesOK handles this case with default header values.

OK
*/
type DeleteApi24ProtectionGroupsVolumesOK struct {
}

func (o *DeleteApi24ProtectionGroupsVolumesOK) Error() string {
	return fmt.Sprintf("[DELETE /api/2.4/protection-groups/volumes][%d] deleteApi24ProtectionGroupsVolumesOK ", 200)
}

func (o *DeleteApi24ProtectionGroupsVolumesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
