// Code generated by go-swagger; DO NOT EDIT.

package protection_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.dev.purestorage.com/FlashArray/terraform-provider-cbs/cbs/internal/faclient/2.4/models"
)

// GetAPI24ProtectionGroupsTargetsReader is a Reader for the GetAPI24ProtectionGroupsTargets structure.
type GetAPI24ProtectionGroupsTargetsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPI24ProtectionGroupsTargetsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetApi24ProtectionGroupsTargetsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetApi24ProtectionGroupsTargetsOK creates a GetApi24ProtectionGroupsTargetsOK with default headers values
func NewGetApi24ProtectionGroupsTargetsOK() *GetApi24ProtectionGroupsTargetsOK {
	return &GetApi24ProtectionGroupsTargetsOK{}
}

/*GetApi24ProtectionGroupsTargetsOK handles this case with default header values.

OK
*/
type GetApi24ProtectionGroupsTargetsOK struct {
	Payload *models.ProtectionGroupTargetGetResponse
}

func (o *GetApi24ProtectionGroupsTargetsOK) Error() string {
	return fmt.Sprintf("[GET /api/2.4/protection-groups/targets][%d] getApi24ProtectionGroupsTargetsOK  %+v", 200, o.Payload)
}

func (o *GetApi24ProtectionGroupsTargetsOK) GetPayload() *models.ProtectionGroupTargetGetResponse {
	return o.Payload
}

func (o *GetApi24ProtectionGroupsTargetsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProtectionGroupTargetGetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
