// Code generated by go-swagger; DO NOT EDIT.

package protection_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.dev.purestorage.com/FlashArray/terraform-provider-cbs/cbs/internal/faclient/2.4/models"
)

// PatchAPI24ProtectionGroupsReader is a Reader for the PatchAPI24ProtectionGroups structure.
type PatchAPI24ProtectionGroupsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchAPI24ProtectionGroupsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchApi24ProtectionGroupsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPatchApi24ProtectionGroupsOK creates a PatchApi24ProtectionGroupsOK with default headers values
func NewPatchApi24ProtectionGroupsOK() *PatchApi24ProtectionGroupsOK {
	return &PatchApi24ProtectionGroupsOK{}
}

/*PatchApi24ProtectionGroupsOK handles this case with default header values.

OK
*/
type PatchApi24ProtectionGroupsOK struct {
	Payload *models.ProtectionGroupResponse
}

func (o *PatchApi24ProtectionGroupsOK) Error() string {
	return fmt.Sprintf("[PATCH /api/2.4/protection-groups][%d] patchApi24ProtectionGroupsOK  %+v", 200, o.Payload)
}

func (o *PatchApi24ProtectionGroupsOK) GetPayload() *models.ProtectionGroupResponse {
	return o.Payload
}

func (o *PatchApi24ProtectionGroupsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProtectionGroupResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
