// Code generated by go-swagger; DO NOT EDIT.

package dns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/PureStorage-OpenConnect/terraform-provider-cbs/cbs/internal/array/faclient/2.4/models"
)

// NewPatchAPI24DNSParams creates a new PatchAPI24DNSParams object
// with the default values initialized.
func NewPatchAPI24DNSParams() *PatchAPI24DNSParams {
	var ()
	return &PatchAPI24DNSParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchAPI24DNSParamsWithTimeout creates a new PatchAPI24DNSParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchAPI24DNSParamsWithTimeout(timeout time.Duration) *PatchAPI24DNSParams {
	var ()
	return &PatchAPI24DNSParams{

		timeout: timeout,
	}
}

// NewPatchAPI24DNSParamsWithContext creates a new PatchAPI24DNSParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchAPI24DNSParamsWithContext(ctx context.Context) *PatchAPI24DNSParams {
	var ()
	return &PatchAPI24DNSParams{

		Context: ctx,
	}
}

// NewPatchAPI24DNSParamsWithHTTPClient creates a new PatchAPI24DNSParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchAPI24DNSParamsWithHTTPClient(client *http.Client) *PatchAPI24DNSParams {
	var ()
	return &PatchAPI24DNSParams{
		HTTPClient: client,
	}
}

/*PatchAPI24DNSParams contains all the parameters to send to the API endpoint
for the patch API 24 DNS operation typically these are written to a http.Request
*/
type PatchAPI24DNSParams struct {

	/*Authorization
	  Access token (in JWT format) required to use any API endpoint (except `/oauth2`, `/login`, and `/logout`)

	*/
	Authorization *string
	/*XRequestID
	  Supplied by client during request or generated by server.

	*/
	XRequestID *string
	/*DNS*/
	DNS *models.DNSPatch

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch API 24 DNS params
func (o *PatchAPI24DNSParams) WithTimeout(timeout time.Duration) *PatchAPI24DNSParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch API 24 DNS params
func (o *PatchAPI24DNSParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch API 24 DNS params
func (o *PatchAPI24DNSParams) WithContext(ctx context.Context) *PatchAPI24DNSParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch API 24 DNS params
func (o *PatchAPI24DNSParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch API 24 DNS params
func (o *PatchAPI24DNSParams) WithHTTPClient(client *http.Client) *PatchAPI24DNSParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch API 24 DNS params
func (o *PatchAPI24DNSParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the patch API 24 DNS params
func (o *PatchAPI24DNSParams) WithAuthorization(authorization *string) *PatchAPI24DNSParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the patch API 24 DNS params
func (o *PatchAPI24DNSParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithXRequestID adds the xRequestID to the patch API 24 DNS params
func (o *PatchAPI24DNSParams) WithXRequestID(xRequestID *string) *PatchAPI24DNSParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the patch API 24 DNS params
func (o *PatchAPI24DNSParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithDNS adds the dns to the patch API 24 DNS params
func (o *PatchAPI24DNSParams) WithDNS(dns *models.DNSPatch) *PatchAPI24DNSParams {
	o.SetDNS(dns)
	return o
}

// SetDNS adds the dns to the patch API 24 DNS params
func (o *PatchAPI24DNSParams) SetDNS(dns *models.DNSPatch) {
	o.DNS = dns
}

// WriteToRequest writes these params to a swagger request
func (o *PatchAPI24DNSParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}

	}

	if o.XRequestID != nil {

		// header param X-Request-ID
		if err := r.SetHeaderParam("X-Request-ID", *o.XRequestID); err != nil {
			return err
		}

	}

	if o.DNS != nil {
		if err := r.SetBodyParam(o.DNS); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
