// Code generated by go-swagger; DO NOT EDIT.

package remote_pods

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.dev.purestorage.com/FlashArray/terraform-provider-cbs/cbs/internal/faclient/2.4/models"
)

// GetAPI24RemotePodsReader is a Reader for the GetAPI24RemotePods structure.
type GetAPI24RemotePodsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPI24RemotePodsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetApi24RemotePodsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetApi24RemotePodsOK creates a GetApi24RemotePodsOK with default headers values
func NewGetApi24RemotePodsOK() *GetApi24RemotePodsOK {
	return &GetApi24RemotePodsOK{}
}

/*GetApi24RemotePodsOK handles this case with default header values.

OK
*/
type GetApi24RemotePodsOK struct {
	Payload *models.RemotePodsResponse
}

func (o *GetApi24RemotePodsOK) Error() string {
	return fmt.Sprintf("[GET /api/2.4/remote-pods][%d] getApi24RemotePodsOK  %+v", 200, o.Payload)
}

func (o *GetApi24RemotePodsOK) GetPayload() *models.RemotePodsResponse {
	return o.Payload
}

func (o *GetApi24RemotePodsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RemotePodsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
