// Code generated by go-swagger; DO NOT EDIT.

package authorization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIAPIVersionParams creates a new GetAPIAPIVersionParams object
// with the default values initialized.
func NewGetAPIAPIVersionParams() *GetAPIAPIVersionParams {

	return &GetAPIAPIVersionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIAPIVersionParamsWithTimeout creates a new GetAPIAPIVersionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIAPIVersionParamsWithTimeout(timeout time.Duration) *GetAPIAPIVersionParams {

	return &GetAPIAPIVersionParams{

		timeout: timeout,
	}
}

// NewGetAPIAPIVersionParamsWithContext creates a new GetAPIAPIVersionParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIAPIVersionParamsWithContext(ctx context.Context) *GetAPIAPIVersionParams {

	return &GetAPIAPIVersionParams{

		Context: ctx,
	}
}

// NewGetAPIAPIVersionParamsWithHTTPClient creates a new GetAPIAPIVersionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIAPIVersionParamsWithHTTPClient(client *http.Client) *GetAPIAPIVersionParams {

	return &GetAPIAPIVersionParams{
		HTTPClient: client,
	}
}

/*GetAPIAPIVersionParams contains all the parameters to send to the API endpoint
for the get API API version operation typically these are written to a http.Request
*/
type GetAPIAPIVersionParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API API version params
func (o *GetAPIAPIVersionParams) WithTimeout(timeout time.Duration) *GetAPIAPIVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API API version params
func (o *GetAPIAPIVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API API version params
func (o *GetAPIAPIVersionParams) WithContext(ctx context.Context) *GetAPIAPIVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API API version params
func (o *GetAPIAPIVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API API version params
func (o *GetAPIAPIVersionParams) WithHTTPClient(client *http.Client) *GetAPIAPIVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API API version params
func (o *GetAPIAPIVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIAPIVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
