// Code generated by go-swagger; DO NOT EDIT.

package network_interfaces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/PureStorage-OpenConnect/terraform-provider-cbs/cbs/internal/array/faclient/2.4/models"
)

// GetAPI24NetworkInterfacesReader is a Reader for the GetAPI24NetworkInterfaces structure.
type GetAPI24NetworkInterfacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPI24NetworkInterfacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetApi24NetworkInterfacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetApi24NetworkInterfacesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetApi24NetworkInterfacesOK creates a GetApi24NetworkInterfacesOK with default headers values
func NewGetApi24NetworkInterfacesOK() *GetApi24NetworkInterfacesOK {
	return &GetApi24NetworkInterfacesOK{}
}

/*GetApi24NetworkInterfacesOK handles this case with default header values.

OK
*/
type GetApi24NetworkInterfacesOK struct {
	Payload *models.NetworkInterfaceGetResponse
}

func (o *GetApi24NetworkInterfacesOK) Error() string {
	return fmt.Sprintf("[GET /api/2.4/network-interfaces][%d] getApi24NetworkInterfacesOK  %+v", 200, o.Payload)
}

func (o *GetApi24NetworkInterfacesOK) GetPayload() *models.NetworkInterfaceGetResponse {
	return o.Payload
}

func (o *GetApi24NetworkInterfacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NetworkInterfaceGetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApi24NetworkInterfacesBadRequest creates a GetApi24NetworkInterfacesBadRequest with default headers values
func NewGetApi24NetworkInterfacesBadRequest() *GetApi24NetworkInterfacesBadRequest {
	return &GetApi24NetworkInterfacesBadRequest{}
}

/*GetApi24NetworkInterfacesBadRequest handles this case with default header values.

BadRequest
*/
type GetApi24NetworkInterfacesBadRequest struct {
	Payload *models.Error
}

func (o *GetApi24NetworkInterfacesBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/2.4/network-interfaces][%d] getApi24NetworkInterfacesBadRequest  %+v", 400, o.Payload)
}

func (o *GetApi24NetworkInterfacesBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetApi24NetworkInterfacesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
