// Code generated by go-swagger; DO NOT EDIT.

package network_interfaces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.dev.purestorage.com/FlashArray/terraform-provider-cbs/cbs/internal/array/faclient/2.4/models"
)

// GetAPI24NetworkInterfacesPerformanceReader is a Reader for the GetAPI24NetworkInterfacesPerformance structure.
type GetAPI24NetworkInterfacesPerformanceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPI24NetworkInterfacesPerformanceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetApi24NetworkInterfacesPerformanceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetApi24NetworkInterfacesPerformanceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetApi24NetworkInterfacesPerformanceOK creates a GetApi24NetworkInterfacesPerformanceOK with default headers values
func NewGetApi24NetworkInterfacesPerformanceOK() *GetApi24NetworkInterfacesPerformanceOK {
	return &GetApi24NetworkInterfacesPerformanceOK{}
}

/*GetApi24NetworkInterfacesPerformanceOK handles this case with default header values.

OK
*/
type GetApi24NetworkInterfacesPerformanceOK struct {
	Payload *models.NetworkInterfacePerformanceGetResponse
}

func (o *GetApi24NetworkInterfacesPerformanceOK) Error() string {
	return fmt.Sprintf("[GET /api/2.4/network-interfaces/performance][%d] getApi24NetworkInterfacesPerformanceOK  %+v", 200, o.Payload)
}

func (o *GetApi24NetworkInterfacesPerformanceOK) GetPayload() *models.NetworkInterfacePerformanceGetResponse {
	return o.Payload
}

func (o *GetApi24NetworkInterfacesPerformanceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NetworkInterfacePerformanceGetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApi24NetworkInterfacesPerformanceBadRequest creates a GetApi24NetworkInterfacesPerformanceBadRequest with default headers values
func NewGetApi24NetworkInterfacesPerformanceBadRequest() *GetApi24NetworkInterfacesPerformanceBadRequest {
	return &GetApi24NetworkInterfacesPerformanceBadRequest{}
}

/*GetApi24NetworkInterfacesPerformanceBadRequest handles this case with default header values.

BadRequest
*/
type GetApi24NetworkInterfacesPerformanceBadRequest struct {
	Payload *models.Error
}

func (o *GetApi24NetworkInterfacesPerformanceBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/2.4/network-interfaces/performance][%d] getApi24NetworkInterfacesPerformanceBadRequest  %+v", 400, o.Payload)
}

func (o *GetApi24NetworkInterfacesPerformanceBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetApi24NetworkInterfacesPerformanceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
