// Code generated by go-swagger; DO NOT EDIT.

package array_connections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPI24ArrayConnectionsConnectionKeyParams creates a new GetAPI24ArrayConnectionsConnectionKeyParams object
// with the default values initialized.
func NewGetAPI24ArrayConnectionsConnectionKeyParams() *GetAPI24ArrayConnectionsConnectionKeyParams {

	return &GetAPI24ArrayConnectionsConnectionKeyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPI24ArrayConnectionsConnectionKeyParamsWithTimeout creates a new GetAPI24ArrayConnectionsConnectionKeyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPI24ArrayConnectionsConnectionKeyParamsWithTimeout(timeout time.Duration) *GetAPI24ArrayConnectionsConnectionKeyParams {

	return &GetAPI24ArrayConnectionsConnectionKeyParams{

		timeout: timeout,
	}
}

// NewGetAPI24ArrayConnectionsConnectionKeyParamsWithContext creates a new GetAPI24ArrayConnectionsConnectionKeyParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPI24ArrayConnectionsConnectionKeyParamsWithContext(ctx context.Context) *GetAPI24ArrayConnectionsConnectionKeyParams {

	return &GetAPI24ArrayConnectionsConnectionKeyParams{

		Context: ctx,
	}
}

// NewGetAPI24ArrayConnectionsConnectionKeyParamsWithHTTPClient creates a new GetAPI24ArrayConnectionsConnectionKeyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPI24ArrayConnectionsConnectionKeyParamsWithHTTPClient(client *http.Client) *GetAPI24ArrayConnectionsConnectionKeyParams {

	return &GetAPI24ArrayConnectionsConnectionKeyParams{
		HTTPClient: client,
	}
}

/*GetAPI24ArrayConnectionsConnectionKeyParams contains all the parameters to send to the API endpoint
for the get API 24 array connections connection key operation typically these are written to a http.Request
*/
type GetAPI24ArrayConnectionsConnectionKeyParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API 24 array connections connection key params
func (o *GetAPI24ArrayConnectionsConnectionKeyParams) WithTimeout(timeout time.Duration) *GetAPI24ArrayConnectionsConnectionKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API 24 array connections connection key params
func (o *GetAPI24ArrayConnectionsConnectionKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API 24 array connections connection key params
func (o *GetAPI24ArrayConnectionsConnectionKeyParams) WithContext(ctx context.Context) *GetAPI24ArrayConnectionsConnectionKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API 24 array connections connection key params
func (o *GetAPI24ArrayConnectionsConnectionKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API 24 array connections connection key params
func (o *GetAPI24ArrayConnectionsConnectionKeyParams) WithHTTPClient(client *http.Client) *GetAPI24ArrayConnectionsConnectionKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API 24 array connections connection key params
func (o *GetAPI24ArrayConnectionsConnectionKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPI24ArrayConnectionsConnectionKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
