// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HostGroupPatch host group patch
//
// swagger:model hostGroupPatch
type HostGroupPatch struct {
	NewName
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *HostGroupPatch) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 NewName
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.NewName = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m HostGroupPatch) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.NewName)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this host group patch
func (m *HostGroupPatch) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with NewName
	if err := m.NewName.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *HostGroupPatch) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HostGroupPatch) UnmarshalBinary(b []byte) error {
	var res HostGroupPatch
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
