// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MaintenanceWindowOAIGenAllOf1 The period of time during which maintenance will occur. Alerts are suppressed during the maintenance window.
//
// swagger:model maintenanceWindowOaiGenAllOf1
type MaintenanceWindowOAIGenAllOf1 struct {

	// The maintenance window start time, measured in milliseconds since the UNIX epoch.
	// Read Only: true
	Created int64 `json:"created,omitempty"`

	// The maintenance window end time, measured in milliseconds since the UNIX epoch.
	// Read Only: true
	Expires int64 `json:"expires,omitempty"`
}

// Validate validates this maintenance window Oai gen all of1
func (m *MaintenanceWindowOAIGenAllOf1) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MaintenanceWindowOAIGenAllOf1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MaintenanceWindowOAIGenAllOf1) UnmarshalBinary(b []byte) error {
	var res MaintenanceWindowOAIGenAllOf1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
