// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PageInfoAllOf0 page info all of0
//
// swagger:model pageInfoAllOf0
type PageInfoAllOf0 struct {

	// Returns a value of `true` if subsequent items can be retrieved.
	MoreItemsRemaining bool `json:"more_items_remaining,omitempty"`

	// The total number of records after applying all filter query parameters. The `total_item_count` will be calculated if and only if the corresponding query parameter `total_item_count` is set to `true`. If this query parameter is not set or set to `false`, a value of `null` will be returned.
	TotalItemCount int32 `json:"total_item_count,omitempty"`
}

// Validate validates this page info all of0
func (m *PageInfoAllOf0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PageInfoAllOf0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PageInfoAllOf0) UnmarshalBinary(b []byte) error {
	var res PageInfoAllOf0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
