// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PodReplicaLinkLag pod replica link lag
//
// swagger:model PodReplicaLinkLag
type PodReplicaLinkLag struct {
	BuiltInRelationship

	PodReplicaLinkLagOAIGenAllOf1
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *PodReplicaLinkLag) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 BuiltInRelationship
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.BuiltInRelationship = aO0

	// AO1
	var aO1 PodReplicaLinkLagOAIGenAllOf1
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.PodReplicaLinkLagOAIGenAllOf1 = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m PodReplicaLinkLag) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.BuiltInRelationship)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.PodReplicaLinkLagOAIGenAllOf1)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this pod replica link lag
func (m *PodReplicaLinkLag) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with BuiltInRelationship
	if err := m.BuiltInRelationship.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with PodReplicaLinkLagOAIGenAllOf1
	if err := m.PodReplicaLinkLagOAIGenAllOf1.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PodReplicaLinkLag) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PodReplicaLinkLag) UnmarshalBinary(b []byte) error {
	var res PodReplicaLinkLag
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
