// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PolicyMemberPostMembersItemsMember Reference to the resource to which the policy may be applied. The `id` or `name` parameter is required, but cannot be set together. If the `name` parameter is set, `resource_type` must also be set.
//
// swagger:model policyMemberPostMembersItemsMember
type PolicyMemberPostMembersItemsMember struct {
	ReferenceWithType
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *PolicyMemberPostMembersItemsMember) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 ReferenceWithType
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.ReferenceWithType = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m PolicyMemberPostMembersItemsMember) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.ReferenceWithType)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this policy member post members items member
func (m *PolicyMemberPostMembersItemsMember) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with ReferenceWithType
	if err := m.ReferenceWithType.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PolicyMemberPostMembersItemsMember) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PolicyMemberPostMembersItemsMember) UnmarshalBinary(b []byte) error {
	var res PolicyMemberPostMembersItemsMember
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
