// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Port port
//
// swagger:model Port
type Port struct {
	BuiltInResourceNoID

	PortCommon

	PortOAIGenAllOf2
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *Port) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 BuiltInResourceNoID
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.BuiltInResourceNoID = aO0

	// AO1
	var aO1 PortCommon
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.PortCommon = aO1

	// AO2
	var aO2 PortOAIGenAllOf2
	if err := swag.ReadJSON(raw, &aO2); err != nil {
		return err
	}
	m.PortOAIGenAllOf2 = aO2

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m Port) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 3)

	aO0, err := swag.WriteJSON(m.BuiltInResourceNoID)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.PortCommon)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	aO2, err := swag.WriteJSON(m.PortOAIGenAllOf2)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO2)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this port
func (m *Port) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with BuiltInResourceNoID
	if err := m.BuiltInResourceNoID.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with PortCommon
	if err := m.PortCommon.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with PortOAIGenAllOf2
	if err := m.PortOAIGenAllOf2.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Port) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Port) UnmarshalBinary(b []byte) error {
	var res Port
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
