// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostOauth210TokenBadRequestBody post oauth210 token bad request body
//
// swagger:model postOauth210TokenBadRequestBody
type PostOauth210TokenBadRequestBody struct {

	// error
	Error string `json:"error,omitempty"`

	// error description
	ErrorDescription string `json:"error_description,omitempty"`
}

// Validate validates this post oauth210 token bad request body
func (m *PostOauth210TokenBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostOauth210TokenBadRequestBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostOauth210TokenBadRequestBody) UnmarshalBinary(b []byte) error {
	var res PostOauth210TokenBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
