// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProtectionGroupOAIGenAllOf1SnapshotSchedule The schedule settings for protection group snapshots.
//
// swagger:model protectionGroupOaiGenAllOf1SnapshotSchedule
type ProtectionGroupOAIGenAllOf1SnapshotSchedule struct {
	SnapshotSchedule
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ProtectionGroupOAIGenAllOf1SnapshotSchedule) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 SnapshotSchedule
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.SnapshotSchedule = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ProtectionGroupOAIGenAllOf1SnapshotSchedule) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.SnapshotSchedule)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this protection group Oai gen all of1 snapshot schedule
func (m *ProtectionGroupOAIGenAllOf1SnapshotSchedule) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with SnapshotSchedule
	if err := m.SnapshotSchedule.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ProtectionGroupOAIGenAllOf1SnapshotSchedule) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProtectionGroupOAIGenAllOf1SnapshotSchedule) UnmarshalBinary(b []byte) error {
	var res ProtectionGroupOAIGenAllOf1SnapshotSchedule
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
