// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RemoteVolumeSnapshotTransfer remote volume snapshot transfer
//
// swagger:model RemoteVolumeSnapshotTransfer
type RemoteVolumeSnapshotTransfer struct {
	Resource

	Transfer

	RemoteVolumeSnapshotTransferAllOf2
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *RemoteVolumeSnapshotTransfer) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 Resource
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.Resource = aO0

	// AO1
	var aO1 Transfer
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.Transfer = aO1

	// AO2
	var aO2 RemoteVolumeSnapshotTransferAllOf2
	if err := swag.ReadJSON(raw, &aO2); err != nil {
		return err
	}
	m.RemoteVolumeSnapshotTransferAllOf2 = aO2

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m RemoteVolumeSnapshotTransfer) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 3)

	aO0, err := swag.WriteJSON(m.Resource)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.Transfer)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	aO2, err := swag.WriteJSON(m.RemoteVolumeSnapshotTransferAllOf2)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO2)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this remote volume snapshot transfer
func (m *RemoteVolumeSnapshotTransfer) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with Resource
	if err := m.Resource.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with Transfer
	if err := m.Transfer.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with RemoteVolumeSnapshotTransferAllOf2

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *RemoteVolumeSnapshotTransfer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RemoteVolumeSnapshotTransfer) UnmarshalBinary(b []byte) error {
	var res RemoteVolumeSnapshotTransfer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// RemoteVolumeSnapshotTransferAllOf2 The transfer statistics for snapshot replication data.
//
// swagger:model RemoteVolumeSnapshotTransferAllOf2
type RemoteVolumeSnapshotTransferAllOf2 interface{}
