// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ArrayPerformance array performance
//
// swagger:model ArrayPerformance
type ArrayPerformance struct {
	Performance

	BuiltIn

	ArrayPerformanceOAIGenAllOf2
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ArrayPerformance) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 Performance
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.Performance = aO0

	// AO1
	var aO1 BuiltIn
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.BuiltIn = aO1

	// AO2
	var aO2 ArrayPerformanceOAIGenAllOf2
	if err := swag.ReadJSON(raw, &aO2); err != nil {
		return err
	}
	m.ArrayPerformanceOAIGenAllOf2 = aO2

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ArrayPerformance) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 3)

	aO0, err := swag.WriteJSON(m.Performance)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.BuiltIn)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	aO2, err := swag.WriteJSON(m.ArrayPerformanceOAIGenAllOf2)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO2)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this array performance
func (m *ArrayPerformance) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with Performance
	if err := m.Performance.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with BuiltIn
	if err := m.BuiltIn.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with ArrayPerformanceOAIGenAllOf2
	if err := m.ArrayPerformanceOAIGenAllOf2.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ArrayPerformance) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ArrayPerformance) UnmarshalBinary(b []byte) error {
	var res ArrayPerformance
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
