// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RemoteProtectionGroupSnapshotPost remote protection group snapshot post
//
// swagger:model remoteProtectionGroupSnapshotPost
type RemoteProtectionGroupSnapshotPost struct {
	BuiltIn

	RemoteProtectionGroupSnapshot

	RemoteProtectionGroupSnapshotPostAllOf2
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *RemoteProtectionGroupSnapshotPost) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 BuiltIn
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.BuiltIn = aO0

	// AO1
	var aO1 RemoteProtectionGroupSnapshot
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.RemoteProtectionGroupSnapshot = aO1

	// AO2
	var aO2 RemoteProtectionGroupSnapshotPostAllOf2
	if err := swag.ReadJSON(raw, &aO2); err != nil {
		return err
	}
	m.RemoteProtectionGroupSnapshotPostAllOf2 = aO2

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m RemoteProtectionGroupSnapshotPost) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 3)

	aO0, err := swag.WriteJSON(m.BuiltIn)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.RemoteProtectionGroupSnapshot)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	aO2, err := swag.WriteJSON(m.RemoteProtectionGroupSnapshotPostAllOf2)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO2)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this remote protection group snapshot post
func (m *RemoteProtectionGroupSnapshotPost) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with BuiltIn
	if err := m.BuiltIn.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with RemoteProtectionGroupSnapshot
	if err := m.RemoteProtectionGroupSnapshot.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with RemoteProtectionGroupSnapshotPostAllOf2
	if err := m.RemoteProtectionGroupSnapshotPostAllOf2.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *RemoteProtectionGroupSnapshotPost) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RemoteProtectionGroupSnapshotPost) UnmarshalBinary(b []byte) error {
	var res RemoteProtectionGroupSnapshotPost
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
