// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RemoteProtectionGroupOAIGenAllOf1TargetRetention The retention policy for the remote protection group.
//
// swagger:model remoteProtectionGroupOaiGenAllOf1TargetRetention
type RemoteProtectionGroupOAIGenAllOf1TargetRetention struct {
	RetentionPolicy
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *RemoteProtectionGroupOAIGenAllOf1TargetRetention) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 RetentionPolicy
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.RetentionPolicy = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m RemoteProtectionGroupOAIGenAllOf1TargetRetention) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.RetentionPolicy)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this remote protection group Oai gen all of1 target retention
func (m *RemoteProtectionGroupOAIGenAllOf1TargetRetention) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with RetentionPolicy
	if err := m.RetentionPolicy.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *RemoteProtectionGroupOAIGenAllOf1TargetRetention) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RemoteProtectionGroupOAIGenAllOf1TargetRetention) UnmarshalBinary(b []byte) error {
	var res RemoteProtectionGroupOAIGenAllOf1TargetRetention
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
