// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SyslogServerSettings Global settings for syslog servers.
//
// swagger:model SyslogServerSettings
type SyslogServerSettings struct {

	// The certificate of the certificate authority (CA) that signed the certificate(s) of the directory server, which is used to validate the authenticity of the configured servers.
	CaCertificate string `json:"ca_certificate,omitempty"`

	// Returns a value of `true` if messages that are necessary in order to audit TLS negotiations performed by the array are forwarded to the configured syslog servers.
	TLSAuditEnabled bool `json:"tls_audit_enabled,omitempty"`
}

// Validate validates this syslog server settings
func (m *SyslogServerSettings) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SyslogServerSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SyslogServerSettings) UnmarshalBinary(b []byte) error {
	var res SyslogServerSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
